# This viminfo file was generated by Vim 7.3.
# You may edit it if you're careful!

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~h
# Last Search Pattern:
~MSle0/hpp

# Last Substitute Search Pattern:
~MSle0~&Interpreter

# Last Substitute String:
$

# Command Line History (newest to oldest):
:q
:e home_automation_system.hpp
:e home_automation_system.cpp
:wq!
:wq
:bw
:w
:%s/Interpreter/HomeAutomationSystem/ge
:e home_automation_system.*
:qa
:q:q
:q!
:qa!
:e ../julius/juliuslibTest/test.cpp
:e julius.cpp
:make
:set nopaste
:set paste
:wu
:%s/callback&/callback/ge

# Search String History (newest to oldest):
? \s\+$
? Interpreter
?/hpp
? \<ÊñáÁ´†\>
?/Julius
?/julius
?/invalid
?/inavalid
?/adin_thread_cancel
? callback&
? <\\n>
? const call
? const callback
? boost::function<void\(Recog*, void*\)>
?/aaaaaaaa/
?/a/
?//
? \/\*\*
? \]
? \[

# Expression History (newest to oldest):
====================================================================================================

# Input Line History (newest to oldest):
@y
@n
@JuliusTest2
@b 70
@file output
@file test
@p
@p *$6
@b 23
@r
@p tagger
@b 29
@q
@process_list =
@**
@OncSentence
@findYomi
@Thread
@JuliusLibTest
@CommitRule

# Input Line History (newest to oldest):

# Registers:
"0	LINE	0
		 * @param [in] cmd	„Ç≥„Éû„É≥„ÉâÔºàe.g. „ÉÜ„É¨„Éì„ÇíÊ∂à„Åó„Å¶Ôºâ
""1	LINE	0
	
"2	CHAR	0
	„Å¶
"3	CHAR	0
	„Åó
"4	CHAR	0
	Ê∂à
"5	CHAR	0
	„Çí
"6	CHAR	0
	„Éì
"7	CHAR	0
	„É¨
"8	CHAR	0
	„ÉÜ
"9	CHAR	0
	 
"d	CHAR	0
	1269
<dddkkkkkkkkkkkkkkkkkkjjjjjjjjjjjjjjjjjjjkjjjjjjjjjjjjjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkkhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxiir_sendlllllllllllllllllllllxxxxinum	ÄkbÄkbÄkbÄkbÄkbÄkbÄkbÄkbÄkbÄkbÄkbÄkbÄkbÄkbÄkbÄkbÄkbÄkbÄkbÄkb int num	ÄkbÄkbÄkbÄkbÄkbÄkbnumjÄkbjjjjjjjjjkddddVjjjdjlllllllllllllllllhhxxxkkkkkkkkkkkkkkkkkhhhhhhhhhhhhhhhhhhhhxxxxxxxxxxÄkblllllllhhhhhhiÄkb ljhhhhhhhhhhhhhhhhhhhhhhhiÄkbÄkbÄkbÄkbÄkbÄkbÄkbÄkbÄkbÄkbÄkbÄkbÄkbtlxxxxxxxxxxxxxxxxxxxxxxxxxxxxjjkkkkkkddddjhhi_jjjjjjjjjjjjjkVjjjdkkkkkkpkddkkkkkkoip::tcp::io	 s_;jjjjjjkkjjjjjllli_hhhhhhhhhhhhhhhhhhhxxxxxxxxxxxxxxxxxxxxxxxxxas.\ÄkbÄkb_.Äkb..ÄkbÄkb.connect(ep);jjjjjjjkddjostd::cout << "ÄkbÄkbÄkbÄkbÄkbÄkbÄkbÄkbÄkbÄkbÄkb::string cmd = "*is;" + num + "\r\n";jhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxxxxxxxxxxxxxxxxxicmdkocÄkbstd;;:cÄkbÄkbÄkbÄkb::cout << cmd << std::endl;ÄklÄklÄklÄklÄklÄklÄklÄklÄklÄklÄklÄklÄklÄklÄklÄklÄklÄklÄklÄklÄklÄklÄklÄkrÄkrÄkrÄkrÄkrÄkr"COMMAND: " << ÄklÄklÄklÄklÄklÄklÄklÄ#4Ä#4Ä#4ÄkrÄkrÄkrÄkrxxxhhxdwiIRjkhlliEMOCONj:qÄkbwkkkkkkkkkkkkkkkkkjjjjjjjjo~iRe	(){}ka		s?Äkb_.close();jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjkkVjjjjjjjjjjjjjjkkjdddjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkVjjjjjjjjjjjjjjjjjjjjjjjjjjkkkjdiwuuVjjjjjjjjjjjjjjjjjjjjjgiwkkkkjj
"j	CHAR	0
	:qjjjjjjjjjjjjjjjjjjjlllllllllllllBkkjjjjjrR
"k@	CHAR	0
	jk
"q	CHAR	0
	:qkkk
"r	CHAR	0
	jjjjkkk
"x	CHAR	0
	xxxÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrÄkrxxxx;w
"-	CHAR	0
	/

# File marks:
'0  1  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.hpp
'1  43  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
'2  1  0  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/main.cpp
'3  36  0  ~/Dropbox/Program/cpp/HAS/interpreter.cpp
'4  1  0  ~/Dropbox/Program/cpp/HAS/main.cpp
'5  1  0  ~/Dropbox/Program/cpp/HAS/julius_client.cpp
'6  36  0  ~/Dropbox/Program/cpp/HAS/interpreter.cpp
'7  1503  0  ~/Dropbox/Program/cpp/HAS/has.doxygen
'8  16  0  ~/Dropbox/Program/cpp/HAS/iRemocon/interpreter.cpp
'9  3  61  ~/Dropbox/Program/cpp/HAS/gram/commands.xml

# Jumplist (newest first):
-'  1  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.hpp
-'  1  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  1  0  ~/Dropbox/Program/cpp/HAS/*unite* - default@1
-'  1  0  ~/Dropbox/Program/cpp/HAS/main.cpp
-'  56  0  ~/Dropbox/Program/cpp/HAS/interpreter.cpp
-'  43  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  10  25  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  19  3  ~/Dropbox/Program/cpp/HAS/interpreter.hpp
-'  8  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  1  0  ~/Dropbox/Program/cpp/HAS/interpreter.cpp
-'  2  0  ~/Dropbox/Program/cpp/HAS/interpreter.cpp
-'  3  0  ~/Dropbox/Program/cpp/HAS/interpreter.cpp
-'  4  0  ~/Dropbox/Program/cpp/HAS/interpreter.cpp
-'  5  0  ~/Dropbox/Program/cpp/HAS/interpreter.cpp
-'  6  0  ~/Dropbox/Program/cpp/HAS/interpreter.cpp
-'  7  0  ~/Dropbox/Program/cpp/HAS/interpreter.cpp
-'  8  0  ~/Dropbox/Program/cpp/HAS/interpreter.cpp
-'  9  0  ~/Dropbox/Program/cpp/HAS/interpreter.cpp
-'  20  49  ~/Dropbox/Program/cpp/HAS/interpreter.hpp
-'  34  13  ~/Dropbox/Program/cpp/HAS/interpreter.hpp
-'  1  0  ~/Dropbox/Program/cpp/HAS/iremocon_client.hpp
-'  1  0  ~/Dropbox/Program/cpp/HAS/iremocon_client.cpp
-'  9  10  ~/Dropbox/Program/cpp/HAS/interpreter.hpp
-'  7  0  ~/Dropbox/Program/cpp/HAS/main.cpp
-'  1  0  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/main.cpp
-'  64  2  ~/Dropbox/Program/cpp/julius/juliuslibTest/test.cpp
-'  61  0  ~/Dropbox/Program/cpp/HAS/iremocon_client.cpp
-'  3  0  ~/Dropbox/Program/cpp/HAS/interpreter.hpp
-'  6  0  ~/Dropbox/Program/cpp/HAS/julius.hpp
-'  98  23  ~/Dropbox/Program/cpp/HAS/julius.hpp
-'  8  0  ~/Dropbox/Program/cpp/HAS/julius.hpp
-'  49  0  ~/Dropbox/Program/cpp/HAS/iremocon_client.hpp
-'  7  19  ~/Dropbox/Program/cpp/HAS/julius.hpp
-'  7  0  ~/Dropbox/Program/cpp/HAS/iremocon_client.hpp
-'  9  0  ~/Dropbox/Program/cpp/HAS/julius.hpp
-'  41  2  ~/Dropbox/Program/cpp/HAS/iremocon_client.hpp
-'  92  14  ~/Dropbox/Program/cpp/HAS/julius.hpp
-'  34  0  ~/Dropbox/Program/cpp/HAS/iremocon_client.hpp
-'  20  2  ~/Dropbox/Program/cpp/HAS/iremocon_client.hpp
-'  30  3  ~/Dropbox/Program/cpp/HAS/interpreter.hpp
-'  36  0  ~/Dropbox/Program/cpp/HAS/interpreter.hpp
-'  39  1  ~/Dropbox/Program/cpp/HAS/iremocon_client.hpp
-'  29  0  ~/Dropbox/Program/cpp/HAS/interpreter.hpp
-'  32  1  ~/Dropbox/Program/cpp/HAS/iremocon_client.hpp
-'  27  0  ~/Dropbox/Program/cpp/HAS/julius.hpp
-'  40  0  ~/Dropbox/Program/cpp/HAS/iremocon_client.hpp
-'  36  0  ~/Dropbox/Program/cpp/HAS/interpreter.cpp
-'  13  0  ~/Dropbox/Program/cpp/HAS/interpreter.cpp
-'  19  6  ~/Dropbox/Program/cpp/HAS/iremocon_client.hpp
-'  21  0  ~/Dropbox/Program/cpp/HAS/julius.hpp
-'  17  27  ~/Dropbox/Program/cpp/HAS/iremocon_client.hpp
-'  8  0  ~/Dropbox/Program/cpp/HAS/iremocon_client.hpp
-'  1  0  ~/Dropbox/Program/cpp/HAS/julius.hpp
-'  1  0  ~/Dropbox/Program/cpp/HAS/julius_client.cpp
-'  14  0  ~/Dropbox/Program/cpp/HAS/interpreter.cpp
-'  1503  0  ~/Dropbox/Program/cpp/HAS/has.doxygen
-'  1  0  ~/Dropbox/Program/cpp/HAS/has.doxygen
-'  16  0  ~/Dropbox/Program/cpp/HAS/iRemocon/interpreter.cpp
-'  1  0  ~/Dropbox/Program/cpp/HAS/iRemocon/interpreter.cpp
-'  3  61  ~/Dropbox/Program/cpp/HAS/gram/commands.xml
-'  4  0  ~/Dropbox/Program/cpp/HAS/gram/commands.xml
-'  1  0  ~/Dropbox/Program/cpp/HAS/gram/commands.xml
-'  99  0  ~/Dropbox/Program/cpp/julius/juliuslibTest/test.cpp
-'  59  0  ~/Dropbox/Program/cpp/HAS/julius.cpp
-'  28  3  ~/Dropbox/Program/cpp/HAS/interpreter.hpp
-'  18  3  ~/Dropbox/Program/cpp/HAS/interpreter.hpp
-'  32  51  ~/Dropbox/Program/cpp/HAS/interpreter.hpp

# History of marks within files (newest to oldest):

> ~/Dropbox/Program/cpp/HAS/*unite* - default@1
	"	5	0
	.	3	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	13	0
	+	13	0
	+	1	0
	+	1	0
	+	1	0
	+	3	0

> ~/Dropbox/Program/cpp/HAS/interpreter.cpp
	"	56	0
	.	1	0
	+	9	0
	+	1	0

> ~/Dropbox/Program/cpp/HAS/main.cpp
	"	1	0

> ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
	"	1	0
	^	32	3
	.	33	0
	+	1	0
	+	1	0
	+	1	0
	+	5	0
	+	6	0
	+	1	0
	+	10	0
	+	11	20
	+	10	59
	+	31	3
	+	30	16
	+	3	26
	+	30	53
	+	32	0
	+	33	0

> ~/Dropbox/Program/cpp/HAS/home_automation_system.hpp
	"	1	0
	^	10	13
	.	4	18
	+	1	0
	+	7	0
	+	7	0
	+	1	37
	+	2	37
	+	15	43
	+	13	0
	+	11	1
	+	7	8
	+	11	0
	+	7	8
	+	12	0
	+	11	0
	+	12	8
	+	13	0
	+	5	0
	+	4	29
	+	10	12
	+	4	18
