# This viminfo file was generated by Vim 7.3.
# You may edit it if you're careful!

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~h
# Last Search Pattern:
~MSle0~/start

# Last Substitute Search Pattern:
~MSle0&OLL

# Last Substitute String:
$

# Command Line History (newest to oldest):
:qa
:w
:e julius.cpp
:wq
:qa!
:e test.cpp
:q
:e home_automation_system.hpp
:eq
:e home_automation_system.cpp
:e julius.hpp
:57
:du
:x
:e ../julius/juliuslibTest/test.cpp
:108
:b home_automation_system.cpp:89
:set paste
:e oll.hpp
:x!

# Search String History (newest to oldest):
? \s\+$
?/start
?/julius_
?/iremocon
?/has
?/recog
?/recog_
?/callback
?/func
?/break
?/gdb
?/this_
?/interpret
?/Online
?//oll
?/OLL
?//tool
?/tool
? "
? \^\[

# Expression History (newest to oldest):
====================================================================================================

# Input Line History (newest to oldest):
@Tmp
@p *$1
@p *$2
@p this_
@p *recog
@p recog
@r
@y
@b home:89
@file has
@f has
@b home_automation_system.cpp:89
@Thread
@**
@JuliusLibTest
@CommitRule
@vimrc
@ã‚³ãƒ¼ãƒ’ãƒ¼é£²ã¿ãŸã„
@Jconf
@HECOMI

# Input Line History (newest to oldest):

# Registers:
"0	LINE	0
	// 	julius_->add_result_callback([](Recog* recog, void* this_){
	// 		// callback ã®å¼•æ•°ã‹ã‚‰ this ã‚’å¾©å…ƒ
	// 		HomeAutomationSystem* has = static_cast<HomeAutomationSystem*>(this_);
	// 
	// 		// çµæœã‚’èµ°æŸ»
	// 		for (const RecogProcess *r = recog->process_list; r; r = r->next) {
	// 			WORD_INFO *winfo = r->lm->winfo;
	// 
	// 			for (int n = 0; n < r->result.sentnum; ++n) {
	// 				Sentence s   = r->result.sent[n];
	// 				WORD_ID *seq = s.word;
	// 				int seqnum   = s.word_num;
	// 
	// 				std::string output = "";
	// 				for (int i = 1; i < seqnum-1; ++i) {
	// 					// èªè­˜çµæœã®æ–‡ç« ã‚’å–å¾—
	// 					output += winfo->woutput[seq[i]];
	// 				}
	// 				std::cout << output << std::endl;
	// 
	// 				// ã‚³ãƒãƒ³ãƒ‰ã«å¯¾å¿œã™ã‚‹IRç•ªå·ã‚’ç™ºä¿¡
	// 				auto ir_num = has->interpret(output);
	// 				if (ir_num) {
	// 					has->talk(output + "ã€ã‚’å®Ÿè¡Œã—ã¾ã™");
	// 					std::cout << ir_num << std::endl;
	// 					has->iremocon_->ir_send(ir_num.get());
	// 				}
	// 			}
	// 		}
	// 	}, this);
""1	LINE	0
	
"2	LINE	0
		julius_->
"3	LINE	0
		this->add_result_callback([](Recog* recog, void* this_){
			// callback ã®å¼•æ•°ã‹ã‚‰ this ã‚’å¾©å…ƒ
			// HomeAutomationSystem* has = static_cast<HomeAutomationSystem*>(this_);
	
			// çµæœã‚’èµ°æŸ»
			for (const RecogProcess *r = recog->process_list; r; r = r->next) {
				WORD_INFO *winfo = r->lm->winfo;
	
				for (int n = 0; n < r->result.sentnum; ++n) {
					Sentence s   = r->result.sent[n];
					WORD_ID *seq = s.word;
					int seqnum   = s.word_num;
	
					std::string output = "";
					for (int i = 1; i < seqnum-1; ++i) {
						// èªè­˜çµæœã®æ–‡ç« ã‚’å–å¾—
						output += winfo->woutput[seq[i]];
					}
					std::cout << output << std::endl;
	
					// ã‚³ãƒãƒ³ãƒ‰ã«å¯¾å¿œã™ã‚‹IRç•ªå·ã‚’ç™ºä¿¡
					// auto ir_num = has->interpret(output);
					int ir_num = 1;
					if (ir_num) {
						// has->talk(output + "ã€ã‚’å®Ÿè¡Œã—ã¾ã™");
						std::cout << ir_num << std::endl;
						// has->iremocon_.ir_send(ir_num.get());
					}
				}
			}
		}, this);
"4	LINE	0
		std::cout << "home_automation_system.cpp: " << julius_ << std::endl;
"5	LINE	0
		julius_->add_result_callback([](Recog* recog, void* this_){
			// callback ã®å¼•æ•°ã‹ã‚‰ this ã‚’å¾©å…ƒ
			HomeAutomationSystem* has = static_cast<HomeAutomationSystem*>(this_);
	
			// çµæœã‚’èµ°æŸ»
			for (const RecogProcess *r = recog->process_list; r; r = r->next) {
				WORD_INFO *winfo = r->lm->winfo;
	
				for (int n = 0; n < r->result.sentnum; ++n) {
					Sentence s   = r->result.sent[n];
					WORD_ID *seq = s.word;
					int seqnum   = s.word_num;
	
					std::string output = "";
					for (int i = 1; i < seqnum-1; ++i) {
						// èªè­˜çµæœã®æ–‡ç« ã‚’å–å¾—
						output += winfo->woutput[seq[i]];
					}
					std::cout << output << std::endl;
	
					// ã‚³ãƒãƒ³ãƒ‰ã«å¯¾å¿œã™ã‚‹IRç•ªå·ã‚’ç™ºä¿¡
					auto ir_num = has->interpret(output);
					if (ir_num) {
						has->talk(output + "ã€ã‚’å®Ÿè¡Œã—ã¾ã™");
						std::cout << ir_num << std::endl;
						has->iremocon_->ir_send(ir_num.get());
					}
				}
			}
		}, this);
"6	LINE	0
		julius_->add_result_callback([](Recog* recog, void* this_){
			// callback ã®å¼•æ•°ã‹ã‚‰ this ã‚’å¾©å…ƒ
			HomeAutomationSystem* has = static_cast<HomeAutomationSystem*>(this_);
	
			// çµæœã‚’èµ°æŸ»
			for (const RecogProcess *r = recog->process_list; r; r = r->next) {
				WORD_INFO *winfo = r->lm->winfo;
	
				for (int n = 0; n < r->result.sentnum; ++n) {
					Sentence s   = r->result.sent[n];
					WORD_ID *seq = s.word;
					int seqnum   = s.word_num;
	
					std::string output = "";
					for (int i = 1; i < seqnum-1; ++i) {
						// èªè­˜çµæœã®æ–‡ç« ã‚’å–å¾—
						output += winfo->woutput[seq[i]];
					}
					std::cout << output << std::endl;
	
					// ã‚³ãƒãƒ³ãƒ‰ã«å¯¾å¿œã™ã‚‹IRç•ªå·ã‚’ç™ºä¿¡
					auto ir_num = has->interpret(output);
					if (ir_num) {
						has->talk(output + "ã€ã‚’å®Ÿè¡Œã—ã¾ã™");
						std::cout << ir_num << std::endl;
						has->iremocon_->ir_send(ir_num.get());
					}
				}
			}
		}, this);
"7	LINE	0
		/**
		 * èªè­˜ã•ã›ã‚‹æ–‡ç« ã¨å¯¾å¿œã—ã¦é€ä¿¡ã™ã‚‹ IR ã®ç•ªå·ã‚’æ›¸ã„ãŸ
		 * XML ã‚’èª­ã¿è¾¼ã‚“ã§ãƒãƒƒãƒ—ã«æ ¼ç´ã€‚
		 * @param [in] cmd	ã‚³ãƒãƒ³ãƒ‰ï¼ˆe.g. ãƒ†ãƒ¬ãƒ“ã‚’æ¶ˆã—ã¦ï¼‰
		 * @return			ãƒ•ã‚¡ã‚¤ãƒ«ã®èª­ã¿è¾¼ã¿ã®æˆå¦
		 */
		bool learn_commands_from_xml(const std::string& file_name);
	
"8	LINE	0
		 * @param [in] iremocon	iRemocon ã‚¤ãƒ³ã‚¹ã‚¿ãƒ³ã‚¹
		 * @param [in] julius	Julius ã‚¤ãƒ³ã‚¹ã‚¿ãƒ³ã‚¹
		 * @param [in] open_jtalk	ç™ºè©±ã‚¨ãƒ³ã‚¸ãƒ³ï¼ˆOpenJTalk or GoogleTTSï¼‰
"9	LINE	0
		has.learn_commands_from_xml("julius/gram/commands.xml");
"d	CHAR	0
	1269
<dddkkkkkkkkkkkkkkkkkkjjjjjjjjjjjjjjjjjjjkjjjjjjjjjjjjjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkkhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxiir_sendlllllllllllllllllllllxxxxinum	€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb int num	€kb€kb€kb€kb€kb€kbnumj€kbjjjjjjjjjkddddVjjjdjlllllllllllllllllhhxxxkkkkkkkkkkkkkkkkkhhhhhhhhhhhhhhhhhhhhxxxxxxxxxx€kblllllllhhhhhhi€kb ljhhhhhhhhhhhhhhhhhhhhhhhi€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kbtlxxxxxxxxxxxxxxxxxxxxxxxxxxxxjjkkkkkkddddjhhi_jjjjjjjjjjjjjkVjjjdkkkkkkpkddkkkkkkoip::tcp::io	 s_;jjjjjjkkjjjjjllli_hhhhhhhhhhhhhhhhhhhxxxxxxxxxxxxxxxxxxxxxxxxxas.\€kb€kb_.€kb..€kb€kb.connect(ep);jjjjjjjkddjostd::cout << "€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb::string cmd = "*is;" + num + "\r\n";jhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxxxxxxxxxxxxxxxxxicmdkoc€kbstd;;:c€kb€kb€kb€kb::cout << cmd << std::endl;€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kr€kr€kr€kr€kr€kr"COMMAND: " << €kl€kl€kl€kl€kl€kl€kl€#4€#4€#4€kr€kr€kr€krxxxhhxdwiIRjkhlliEMOCONj:q€kbwkkkkkkkkkkkkkkkkkjjjjjjjjo~iRe	(){}ka		s?€kb_.close();jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjkkVjjjjjjjjjjjjjjkkjdddjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkVjjjjjjjjjjjjjjjjjjjjjjjjjjkkkjdiwuuVjjjjjjjjjjjjjjjjjjjjjgiwkkkkjj
"j	CHAR	0
	jkuuujjjko>>a€kb lit("q€kb|)"(€kb) [phx::push_back(phx::ref(buf)m,€kb€kb, "":€kb]:w\r:qhhhhhlllla):w\r
"k@	CHAR	0
	jk
"q	CHAR	0
	:qkkk
"r	CHAR	0
	jjjjkkk
"x	CHAR	0
	xxx€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€krxxxx;w
"-	CHAR	0
	s

# File marks:
'0  1  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
'1  7  0  ~/Dropbox/Program/cpp/HAS/*unite* - default@1
'2  56  6  ~/Dropbox/Program/cpp/HAS/julius.cpp
'3  117  1  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
'4  16  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
'5  6  25  ~/Dropbox/Program/cpp/HAS/test.cpp
'6  157  27  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
'7  68  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.hpp
'8  168  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
'9  1  0  ~/Dropbox/Program/cpp/HAS/test.cpp

# Jumplist (newest first):
-'  1  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  7  0  ~/Dropbox/Program/cpp/HAS/*unite* - default@1
-'  1  0  ~/Dropbox/Program/cpp/HAS/*unite* - default@1
-'  17  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  56  0  ~/Dropbox/Program/cpp/HAS/julius.cpp
-'  18  9  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  136  39  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  118  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  117  1  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  16  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  6  25  ~/Dropbox/Program/cpp/HAS/test.cpp
-'  61  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.hpp
-'  148  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  157  27  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  112  21  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  159  10  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  158  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  68  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.hpp
-'  1  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.hpp
-'  168  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  1  0  ~/Dropbox/Program/cpp/HAS/test.cpp
-'  7  1  ~/Dropbox/Program/cpp/HAS/test.cpp
-'  13  11  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  5  31  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  4  23  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  55  21  ~/Dropbox/Program/cpp/HAS/home_automation_system.hpp
-'  106  3  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  49  7  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  14  1  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  63  39  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  51  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  27  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.hpp
-'  55  31  ~/Dropbox/Program/cpp/HAS/julius.cpp
-'  68  0  ~/Dropbox/Program/cpp/HAS/julius.hpp
-'  74  0  ~/Dropbox/Program/cpp/HAS/julius.cpp
-'  1  0  ~/Dropbox/Program/cpp/HAS/julius.cpp
-'  33  0  ~/Dropbox/Program/cpp/HAS/julius.cpp
-'  3  0  ~/Dropbox/Program/cpp/HAS/julius
-'  1  0  ~/Dropbox/Program/cpp/HAS/julius
-'  59  0  ~/Dropbox/Program/cpp/HAS/julius.cpp
-'  4  0  ~/Dropbox/Program/cpp/HAS/julius.cpp
-'  71  0  ~/Dropbox/Program/cpp/HAS/julius.cpp
-'  35  0  ~/Dropbox/Program/cpp/julius/juliuslibTest/test.cpp
-'  31  0  ~/Dropbox/Program/cpp/HAS/julius.cpp
-'  85  0  ~/Dropbox/Program/cpp/HAS/julius/test2.cpp
-'  1  0  ~/Dropbox/Program/cpp/HAS/julius/test2.cpp
-'  9  68  ~/Dropbox/Program/cpp/HAS/julius/Makefile
-'  1  0  ~/Dropbox/Program/cpp/HAS/julius/Makefile
-'  11  0  ~/Dropbox/Program/cpp/HAS/julius/Makefile
-'  23  0  ~/Dropbox/Program/cpp/HAS/julius/Makefile
-'  21  0  ~/Dropbox/Program/cpp/HAS/Makefile
-'  1  0  ~/Dropbox/Program/cpp/HAS/Makefile
-'  2  11  ~/Dropbox/Program/cpp/HAS/julius/Makefile
-'  58  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.hpp
-'  1  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.
-'  56  24  ~/Dropbox/Program/cpp/HAS/home_automation_system.hpp
-'  11  44  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  8  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  69  37  ~/Dropbox/Program/cpp/HAS/home_automation_system.hpp
-'  165  54  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  66  39  ~/Dropbox/Program/cpp/HAS/home_automation_system.hpp
-'  69  0  ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
-'  29  1  ~/Dropbox/Program/cpp/HAS/julius.cpp
-'  53  0  ~/Dropbox/Program/cpp/julius/juliuslibTest/test.cpp
-'  95  0  ~/Dropbox/Program/cpp/julius/juliuslibTest/test.cpp
-'  100  0  ~/Dropbox/Program/cpp/julius/juliuslibTest/test.cpp
-'  85  0  ~/Dropbox/Program/cpp/julius/juliuslibTest/test.cpp
-'  75  0  ~/Dropbox/Program/cpp/HAS/julius.cpp
-'  11  0  ~/Dropbox/Program/cpp/HAS/julius.cpp
-'  98  0  ~/Dropbox/Program/cpp/julius/juliuslibTest/test.cpp
-'  36  0  ~/Dropbox/Program/cpp/HAS/julius.cpp
-'  66  0  ~/Dropbox/Program/cpp/julius/juliuslibTest/test.cpp
-'  27  0  ~/Dropbox/Program/cpp/HAS/julius.cpp
-'  1  0  ~/Dropbox/Program/cpp/julius/juliuslibTest/test.cpp
-'  1  0  ~/Dropbox/Program/cpp/julius/juliuslibTest/test.cppp
-'  105  0  ~/Dropbox/Program/cpp/HAS/julius.cpp
-'  87  14  ~/Dropbox/Program/cpp/HAS/julius.hpp
-'  15  45  ~/Dropbox/Program/cpp/HAS/julius.hpp
-'  6  0  ~/Dropbox/Program/cpp/HAS/julius.cpp
-'  83  8  ~/Dropbox/Program/cpp/HAS/julius.cpp
-'  81  41  ~/Dropbox/Program/cpp/HAS/julius.cpp
-'  103  8  ~/Dropbox/Program/cpp/HAS/julius.cpp
-'  101  20  ~/Dropbox/Program/cpp/HAS/julius.cpp
-'  98  29  ~/Dropbox/Program/cpp/HAS/julius.cpp

# History of marks within files (newest to oldest):

> ~/Dropbox/Program/cpp/HAS/home_automation_system.cpp
	"	1	0
	^	18	8
	.	16	0
	+	11	107
	+	11	70
	+	49	0
	+	148	36
	+	116	0
	+	148	2
	+	116	31
	+	148	0
	+	89	0
	+	72	45
	+	89	0
	+	72	0
	+	71	50
	+	148	0
	+	148	67
	+	116	0
	+	148	0
	+	148	0
	+	148	0
	+	148	0
	+	148	0
	+	148	0
	+	148	1
	+	116	0
	+	148	0
	+	148	0
	+	148	0
	+	148	18
	+	148	2
	+	148	44
	+	148	0
	+	148	57
	+	148	0
	+	8	0
	+	8	0
	+	148	8
	+	148	0
	+	148	0
	+	148	0
	+	148	0
	+	148	0
	+	148	43
	+	148	0
	+	148	0
	+	148	0
	+	8	0
	+	8	0
	+	148	44
	+	148	0
	+	148	8
	+	165	54
	+	8	0
	+	8	44
	+	11	43
	+	11	44
	+	11	44
	+	148	0
	+	8	0
	+	148	0
	+	148	0
	+	148	0
	+	148	0
	+	148	0
	+	118	47
	+	13	9
	+	11	43
	+	13	33
	+	14	31
	+	15	35
	+	14	9
	+	13	11
	+	11	43
	+	12	0
	+	148	20
	+	107	8
	+	106	0
	+	107	9
	+	112	9
	+	118	48
	+	148	9
	+	159	9
	+	167	13
	+	13	20
	+	14	20
	+	15	20
	+	5	31
	+	15	11
	+	14	11
	+	13	11
	+	17	1
	+	148	0
	+	16	0
	+	16	0
	+	118	0
	+	117	0
	+	147	0
	+	121	0
	+	18	9
	+	18	0
	+	16	0

> ~/Dropbox/Program/cpp/HAS/*unite* - default@1
	"	3	0
	.	3	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	315	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	39	0
	+	1	0
	+	36	0
	+	1	0
	+	33	0
	+	1	0
	+	30	0
	+	1	0
	+	1	0
	+	1	0
	+	25	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	18	0
	+	14	0
	+	1	0
	+	11	0
	+	1	0
	+	1	0
	+	1	0
	+	7	0
	+	1	0
	+	3	0
