# Shougo-san's plugins {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler'

# [[plugins]]
# repo = 'Shougo/defx.nvim'

# [[plugins]]
# repo = 'Shougo/deol.nvim'

# [[plugins]]
# repo = 'Shougo/deoppet.nvim'
# }}}

# Key {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'houtsnip/vim-emacscommandline'

[[plugins]]
repo = 'LeafCage/yankround.vim'

[[plugins]]
repo = 'thinca/vim-ambicmd'
# }}}

# Appearance {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'hecomi/tsubakumi.vim'

[[plugins]]
repo = 'kien/rainbow_parentheses.vim'

[[plugins]]
repo = 'thinca/vim-splash'
# }}}

# Text-Object {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'

[[plugins]]
repo = 'thinca/vim-textobj-comment'
# }}}
