# Shougo-san's plugins {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['denite.nvim']
# }}}

# Syntax {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
# }}}

# Complete {{{
[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = ['vim']

[[plugins]]
repo = 'ujihisa/neco-look'
on_ft = ['vim']
# }}}

# C / C++ {{{
[[plugins]]
repo = 'vim-scripts/a.vim'
on_ft = ['c', 'cpp']
hook_source = '''
    nmap <silent> <C-t> :A<CR>
'''
# }}}

# CSharp {{{
[[plugins]]
repo = "OmniSharp/omnisharp-vim"
on_ft = ["cs"]
# }}}

# Web {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = ['<Plug>(openbrowser-']
# }}}

# Others {{{
# ---------------------------------------------------------------------------------------------------
[[plugins]]
repo = 'glidenote/memolist.vim'
on_cmd = ['MemoNew', 'MemoList', 'MemoGrep']
# }}}
