# https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh
source ~/.bash/git-prompt.sh

GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
GIT_PS1_SHOWSTASHSTATE=true
GIT_PS1_SHOWUPSTREAM=auto
GIT_PS1_SHOWCOLORHINTS=true
GIT_PS1_DESCRIBE_STYLE=default

PS1_THEME_SYMBOL_SEPARATOR='⮀'
PS1_THEME_SYMBOL_COMMAND='>>'

PS1_THEME_BAR_COLOR_BG='5;40'
PS1_THEME_USR_COLOR_FG='1;37'
PS1_THEME_USR_COLOR_BG='46'
PS1_THEME_USR_COLOR_ARW_FG='0;36'
PS1_THEME_DIR_COLOR_FG='0;37'
PS1_THEME_DIR_COLOR_BG='5;42'
PS1_THEME_DIR_COLOR_ARW_FG='1;32'
PS1_THEME_GIT_COLOR_FG='0;30'
PS1_THEME_GIT_COLOR_BG='5;47'
PS1_THEME_GIT_COLOR_ARW_FG='1;37'
PS1_THEME_CMD_COLOR_FG='0;32'

PS1_THEME_BAR_COLOR='\[\e['$PS1_THEME_BAR_COLOR_BG'm\]'
PS1_THEME_USR_COLOR='\[\e['$PS1_THEME_USR_COLOR_FG';'$PS1_THEME_USR_COLOR_BG'm\]'
PS1_THEME_USR_ARW_COLOR='\[\e['$PS1_THEME_USR_COLOR_ARW_FG';'$PS1_THEME_DIR_COLOR_BG'm\]'
PS1_THEME_DIR_COLOR='\[\e['$PS1_THEME_DIR_COLOR_FG';'$PS1_THEME_DIR_COLOR_BG'm\]'
PS1_THEME_DIR_ARW_COLOR='\[\e['$PS1_THEME_DIR_COLOR_ARW_FG';'$PS1_THEME_GIT_COLOR_BG'm\]'
PS1_THEME_GIT_COLOR='\[\e['$PS1_THEME_GIT_COLOR_FG';'$PS1_THEME_GIT_COLOR_BG'm\]'
PS1_THEME_GIT_ARW_COLOR='\[\e['$PS1_THEME_GIT_COLOR_ARW_FG';'$PS1_THEME_BAR_COLOR_BG'm\]'
PS1_THEME_CMD_COLOR='\[\e['$PS1_THEME_CMD_COLOR_FG'm\]'
PS1_THEME_RESET='\[\e[0;39;49m\]'

PS1_THEME_BAR=$(printf $PS1_THEME_BAR_COLOR"%-$(tput cols)s\r"$PS1_THEME_RESET)
PS1_THEME_USR=$PS1_THEME_USR_COLOR' \u '$PS1_THEME_USR_ARW_COLOR$PS1_THEME_SYMBOL_SEPARATOR
PS1_THEME_DIR=$PS1_THEME_DIR_COLOR' \w '$PS1_THEME_DIR_ARW_COLOR$PS1_THEME_SYMBOL_SEPARATOR
PS1_THEME_GIT=$PS1_THEME_GIT_COLOR' $(__git_ps1 "%s") '$PS1_THEME_GIT_ARW_COLOR$PS1_THEME_SYMBOL_SEPARATOR
PS1_THEME_CMD=$PS1_THEME_CMD_COLOR$PS1_THEME_SYMBOL_COMMAND$PS1_THEME_RESET' '

export PS1=$PS1_THEME_BAR$PS1_THEME_USR$PS1_THEME_DIR$PS1_THEME_GIT$PS1_THEME_RESET$'\n'$PS1_THEME_CMD$PS1_THEME_RESET
