# This viminfo file was generated by Vim 7.2.
# You may edit it if you're careful!

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~h
# Last Search Pattern:
~MSle0~/Thread

# Last Substitute Search Pattern:
~MSle0&â—†

# Last Substitute String:
$

# Command Line History (newest to oldest):
:bw
:q
:wq
:w
:Unite grep
:Unite grep Thread
:Unite gre
:pwd
:VimShellCreate
:e Makefile.bak
:q!
:hhh
:q]
:set paste
:Wq
:set nonumber
:e default.sh
:%s/â—†/*/ge
:cd $HOME
:NeoBundleInstall

# Search String History (newest to oldest):
? \s\+$
?/Thread
?/JuliusStart
?/ã‚¨ãƒ³ã‚¿ãƒ¼
?/MAXPOLLINTERVAL
?/msec
?/Warning
?/g++
? <\\n>
?/bin/sh
?/webapi
? â—†
?/Neo
?/setting
?/reani
?/reanim
? 
? ^M
?/character
?/default

# Expression History (newest to oldest):
====================================================================================================

# Input Line History (newest to oldest):
@JuliusLibTest
@Thread
@**
@CommitRule
@vimrc
@ã‚³ãƒ¼ãƒ’ãƒ¼é£²ã¿ãŸã„
@y
@Jconf

# Input Line History (newest to oldest):

# Registers:
"0	LINE	0
	#!/bin/sh
	
	VOICE=$3
	echo $1 | open_jtalk \
	-td $VOICE/tree-dur.inf \
	-tf $VOICE/tree-lf0.inf \
	-tm $VOICE/tree-mgc.inf \
	-md $VOICE/dur.pdf \
	-mf $VOICE/lf0.pdf \
	-mm $VOICE/mgc.pdf \
	-df $VOICE/lf0.win1 \
	-df $VOICE/lf0.win2 \
	-df $VOICE/lf0.win3 \
	-dm $VOICE/mgc.win1 \
	-dm $VOICE/mgc.win2 \
	-dm $VOICE/mgc.win3 \
	-ef $VOICE/tree-gv-lf0.inf \
	-em $VOICE/tree-gv-mgc.inf \
	-cf $VOICE/gv-lf0.pdf \
	-cm $VOICE/gv-mgc.pdf \
	-k  $VOICE/gv-switch.inf \
	-x /usr/lib/open_jtalk/dic/utf-8 \
	-s 48000 \
	-p 240 \
	-a 0.58 \
	-u 0.0 \
	-jm 0.7 \
	-jf 0.5 \
	-l \
	-z 48000 \
	-ow $2 \
	-ot out.log
	
"1	LINE	0
	
	####
	#### When using system-installed libraries
	####
	# CPPFLAGS=`libjulius-config --cflags` `libsent-config --cflags`
	# LDFLAGS=`libjulius-config --libs` `libsent-config --libs`
	
	####
	#### When using within-package libraries
	####
"2	LINE	0
			WORD_ID *seq;
"3	LINE	0
			
"4	LINE	0
				
"5	LINE	0
	
"6	LINE	0
			WORD_INFO *winfo = r->lm->winfo;
	
			for (int n = 0; n < r->result.sentnum; ++n) {
"7	LINE	0
	
"8	LINE	0
			WORD_INFO *winfo;
"9	LINE	0
				if (!r->live) continue;
"d	CHAR	0
	1269
<dddkkkkkkkkkkkkkkkkkkjjjjjjjjjjjjjjjjjjjkjjjjjjjjjjjjjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkkhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxiir_sendlllllllllllllllllllllxxxxinum	€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb int num	€kb€kb€kb€kb€kb€kbnumj€kbjjjjjjjjjkddddVjjjdjlllllllllllllllllhhxxxkkkkkkkkkkkkkkkkkhhhhhhhhhhhhhhhhhhhhxxxxxxxxxx€kblllllllhhhhhhi€kb ljhhhhhhhhhhhhhhhhhhhhhhhi€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kbtlxxxxxxxxxxxxxxxxxxxxxxxxxxxxjjkkkkkkddddjhhi_jjjjjjjjjjjjjkVjjjdkkkkkkpkddkkkkkkoip::tcp::io	 s_;jjjjjjkkjjjjjllli_hhhhhhhhhhhhhhhhhhhxxxxxxxxxxxxxxxxxxxxxxxxxas.\€kb€kb_.€kb..€kb€kb.connect(ep);jjjjjjjkddjostd::cout << "€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb::string cmd = "*is;" + num + "\r\n";jhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxxxxxxxxxxxxxxxxxicmdkoc€kbstd;;:c€kb€kb€kb€kb::cout << cmd << std::endl;€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kr€kr€kr€kr€kr€kr"COMMAND: " << €kl€kl€kl€kl€kl€kl€kl€#4€#4€#4€kr€kr€kr€krxxxhhxdwiIRjkhlliEMOCONj:q€kbwkkkkkkkkkkkkkkkkkjjjjjjjjo~iRe	(){}ka		s?€kb_.close();jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjkkVjjjjjjjjjjjjjjkkjdddjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkVjjjjjjjjjjjjjjjjjjjjjjjjjjkkkjdiwuuVjjjjjjjjjjjjjjjjjjjjjgiwkkkkjj
"j	CHAR	0
	jkuuujjjko>>a€kb lit("q€kb|)"(€kb) [phx::push_back(phx::ref(buf)m,€kb€kb, "":€kb]:w\r:qhhhhhlllla):w\r
"k@	CHAR	0
	jk
"q	CHAR	0
	:qkkk
"r	CHAR	0
	jjjjkkk
"x	CHAR	0
	xxx€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€krxxxx;w
""-	CHAR	0
	b

# File marks:
'0  1  0  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/main.cpp
'1  68  0  ~/Dropbox/Program/cpp/julius/juliuslibTest/test.cpp
'2  7  0  ~/Dropbox/Program/cpp/julius/juliuslibTest/Makefile
'3  62  20  ~/Dropbox/Program/cpp/julius/juliuslibTest/test.cpp
'4  7  29  ~/Dropbox/Program/cpp/julius/juliuslibTest/README
'5  6  0  ~/Dropbox/Program/cpp/julius/juliuslibTest/Makefile
'6  1  1  ~/Dropbox/Program/cpp/julius/juliuslibTest/julius-4.2.1/julius-simple/Makefile
'7  35  39  ~/Dropbox/Program/cpp/julius/libjulius/test.cpp
'8  1  0  ~/Dropbox/Program/cpp/julius/libjulius/hmm_mono.jconf
'9  33  0  ~/Dropbox/Program/cpp/julius/libjulius/hmm_ptm.jconf

# Jumplist (newest first):
-'  1  0  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/main.cpp
-'  40  1  ~/Dropbox/Program/cpp/julius/juliuslibTest/*vimshell* - 1
-'  1  0  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/JuliusPlusRule.cpp
-'  1  0  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/JuliusPlus.cpp
-'  1  0  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/ActionImplement.cpp
-'  39  10  ~/Dropbox/Program/cpp/julius/juliuslibTest/*vimshell* - 1
-'  38  14  ~/Dropbox/Program/cpp/julius/juliuslibTest/*vimshell* - 1
-'  64  0  ~/Dropbox/Program/cpp/julius/juliuslibTest/test.cpp
-'  1  0  ~/Dropbox/Program/cpp/julius/juliuslibTest/test.cpp
-'  68  0  ~/Dropbox/Program/cpp/julius/juliuslibTest/test.cpp
-'  7  0  ~/Dropbox/Program/cpp/julius/juliuslibTest/Makefile
-'  8  25  ~/Dropbox/Program/cpp/julius/juliuslibTest/Makefile
-'  1  0  ~/Dropbox/Program/cpp/julius/juliuslibTest/Makefile
-'  62  20  ~/Dropbox/Program/cpp/julius/juliuslibTest/test.cpp
-'  6  0  ~/Dropbox/Program/cpp/julius/juliuslibTest/test.cpp
-'  91  0  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/main.cpp
-'  67  0  ~/Dropbox/Program/cpp/julius/juliuslibTest/test.cpp
-'  1108  0  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/JuliusPlus.cpp
-'  66  0  ~/Dropbox/Program/cpp/julius/juliuslibTest/test.cpp
-'  77  0  ~/Dropbox/Program/cpp/julius/juliuslibTest/test.cpp
-'  1204  0  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/JuliusPlus.cpp
-'  58  0  ~/Dropbox/Program/cpp/julius/juliuslibTest/test.cpp
-'  139  0  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/JuliusPlus.h
-'  1141  14  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/JuliusPlus.cpp
-'  1110  8  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/JuliusPlus.cpp
-'  1109  15  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/JuliusPlus.cpp
-'  555  7  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/JuliusPlus.cpp
-'  1209  0  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/JuliusPlus.cpp
-'  1091  7  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/JuliusPlus.cpp
-'  93  0  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/main.cpp
-'  19  0  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/*vimfiler* - default@1
-'  1  0  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/*vimfiler* - default@1
-'  22  52  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/JuliusPlus.cpp
-'  54  0  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/JuliusPlus.cpp
-'  171  0  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/JuliusPlus.cpp
-'  138  1  ~/Dropbox/Program/cpp/julius/juliuslibTest/*vimshell* - 1
-'  137  19  ~/Dropbox/Program/cpp/julius/juliuslibTest/*vimshell* - 1
-'  136  14  ~/Dropbox/Program/cpp/julius/juliuslibTest/*vimshell* - 1
-'  1  2  ~/*vimshell* - 2
-'  46  1  ~/Dropbox/Program/cpp/julius/juliuslibTest/*vimshell* - 1
-'  7  29  ~/Dropbox/Program/cpp/julius/juliuslibTest/README
-'  1  0  ~/Dropbox/Program/cpp/julius/juliuslibTest/README
-'  6  0  ~/Dropbox/Program/cpp/julius/juliuslibTest/Makefile
-'  1  1  ~/Dropbox/Program/cpp/julius/juliuslibTest/julius-4.2.1/julius-simple/Makefile
-'  35  39  ~/Dropbox/Program/cpp/julius/libjulius/test.cpp
-'  39  0  ~/Dropbox/Program/cpp/julius/libjulius/test.cpp
-'  32  45  ~/Dropbox/Program/cpp/julius/libjulius/test.cpp
-'  42  2  ~/Dropbox/Program/cpp/julius/libjulius/test.cpp
-'  1  0  ~/Dropbox/Program/cpp/julius/libjulius/test.cpp
-'  1  0  ~/Dropbox/Program/cpp/julius/libjulius/hmm_mono.jconf
-'  33  0  ~/Dropbox/Program/cpp/julius/libjulius/hmm_ptm.jconf
-'  198  0  ~/Dropbox/Program/cpp/julius/libjulius/hmm_mono.jconf
-'  198  0  ~/Dropbox/Program/cpp/julius/libjulius/hmm_ptm.jconf
-'  6  0  ~/Dropbox/Program/cpp/julius/libjulius/hmm_mono.jconf
-'  1  0  ~/Dropbox/Program/cpp/julius/libjulius/model/phone_m/hmmdefs_monof_mix16_gid.binhmm
-'  129  8  ~/Dropbox/Program/cpp/julius/libjulius/julius-4.2.1/libsent/src/adin/adin_mic_linux_alsa.c
-'  553  69  ~/Dropbox/Program/cpp/julius/libjulius/julius-4.2.1/libsent/src/adin/adin_mic_linux_alsa.c
-'  346  47  ~/Dropbox/Program/cpp/julius/libjulius/julius-4.2.1/libsent/src/adin/adin_mic_linux_alsa.c
-'  342  65  ~/Dropbox/Program/cpp/julius/libjulius/julius-4.2.1/libsent/src/adin/adin_mic_linux_alsa.c
-'  334  39  ~/Dropbox/Program/cpp/julius/libjulius/julius-4.2.1/libsent/src/adin/adin_mic_linux_alsa.c
-'  312  54  ~/Dropbox/Program/cpp/julius/libjulius/julius-4.2.1/libsent/src/adin/adin_mic_linux_alsa.c
-'  292  75  ~/Dropbox/Program/cpp/julius/libjulius/julius-4.2.1/libsent/src/adin/adin_mic_linux_alsa.c
-'  290  29  ~/Dropbox/Program/cpp/julius/libjulius/julius-4.2.1/libsent/src/adin/adin_mic_linux_alsa.c
-'  109  10  ~/Dropbox/Program/cpp/julius/libjulius/julius-4.2.1/libsent/src/adin/adin_mic_linux_alsa.c
-'  1  0  ~/Dropbox/Program/cpp/julius/libjulius/julius-4.2.1/libsent/src/adin/adin_mic_linux_alsa.c
-'  610  1  ~/Dropbox/Program/cpp/julius/libjulius/julius-4.2.1/libsent/src/adin/adin_mic_linux_alsa.c
-'  554  3  ~/Dropbox/Program/cpp/julius/libjulius/julius-4.2.1/libsent/src/adin/adin_mic_linux_alsa.c
-'  62  25  ~/Dropbox/Program/cpp/julius/libjulius/test.cpp
-'  17  109  ~/Dropbox/Program/cpp/julius/libjulius/julius-4.2.1/julius-simple/Makefile
-'  1  0  ~/Dropbox/Program/cpp/julius/libjulius/julius-4.2.1/julius-simple/Makefile
-'  69  0  ~/Dropbox/Program/cpp/julius/libjulius/test.cpp
-'  1  0  ~/Dropbox/Program/cpp/iRemocon/julius/testmic.jconf
-'  1  0  ~/Dropbox/Program/cpp/iRemocon/julius/testfile.jconf
-'  3  0  ~/Dropbox/Program/cpp/julius/libjulius/julius-4.2.1
-'  1  0  ~/Dropbox/Program/cpp/julius/libjulius/julius-4.2.1
-'  2  11  ~/Dropbox/Program/cpp/julius/libjulius/Makefile
-'  1  0  ~/Dropbox/Program/cpp/julius/libjulius/Makefile
-'  1  0  ~/Dropbox/Program/cpp/julius/libjulius/Make
-'  1  0  ~/Dropbox/Program/cpp/julius/libjulius/Makw
-'  2  22  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-simple/Makefile
-'  1  0  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-simple/Makefile
-'  1  0  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-simple/Mask
-'  5  1  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-simple/Makefile
-'  4  1  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-simple/Makefile
-'  31  10  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-simple/Makefile
-'  2  14  ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-simple/Makefile.bak

# History of marks within files (newest to oldest):

> ~/Dropbox/Program/cpp/julius/juliuslibTest/test.cpp
	"	64	0
	^	62	21
	.	62	20
	+	2	26
	+	62	23
	+	63	0
	+	64	0
	+	65	0
	+	62	23
	+	66	0
	+	65	3
	+	67	18
	+	68	25
	+	70	11
	+	62	20

> ~/Dropbox/Program/cpp/julius/juliuslibTest/*unite* - default@1
	"	3	0
	.	3	0
	+	5	0
	+	1	0
	+	3	0

> ~/Dropbox/Program/cpp/julius/juliuslibTest/*vimshell* - 1
	"	39	10
	^	39	11
	.	40	0
	+	1	4
	+	41	0
	+	42	6
	+	43	4
	+	46	12
	+	47	4
	+	48	0
	+	49	8
	+	50	4
	+	52	5
	+	53	14
	+	54	4
	+	66	28
	+	67	4
	+	68	0
	+	70	17
	+	73	4
	+	76	10
	+	77	12
	+	78	4
	+	83	15
	+	84	4
	+	85	0
	+	87	14
	+	90	15
	+	91	4
	+	93	8
	+	94	4
	+	97	17
	+	98	4
	+	99	0
	+	106	16
	+	107	4
	+	114	21
	+	115	0
	+	120	21
	+	136	15
	+	137	20
	+	138	0
	+	1	4
	+	2	0
	+	3	3
	+	6	4
	+	8	4
	+	9	4
	+	10	0
	+	12	52
	+	13	4
	+	18	28
	+	19	4
	+	20	0
	+	27	13
	+	30	16
	+	31	4
	+	38	15
	+	39	11
	+	40	0

> ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/JuliusPlus.cpp
	"	1	0

> ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/JuliusPlus.h
	"	1	0

> ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/JuliusPlusRule.cpp
	"	1	0

> ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/JuliusPlusRule.h
	"	1	0

> ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/JuliusPlus.o
	"	1	0

> ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/ActionImplement.cpp
	"	1	0

> ~/Downloads/rti7743-rtilabs-1c2b069/files/asobiba/juliustest/julius-4.2.1/julius-plus/main.cpp
	"	1	0
