# This viminfo file was generated by Vim 7.3.
# You may edit it if you're careful!

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~h
# Last Search Pattern:
~MSle0~/C-J

# Last Substitute Search Pattern:
~MSle0&4.2.1

# Last Substitute String:
$

# Command Line History (newest to oldest):
:qa
:vsp
:q
:w
:e ../main.js
:wq
:qa!
:!export path
:wqa
:e index.html
:wuuu
:bd
:e socket.io/recog.js
:e main.js
:e node_modules/
:e julius.js
:e node_modules/mecab-async/mecab.js
:e node_modules/julius/test2.js
:27017
:a;

# Search String History (newest to oldest):
?/C-J
? \s\+$
?/socket
?/wavfp
?/fopen
?/local
?/tweet
?/baloon
?/fukidashi
?/stage
?/MODEL
?/loop
?/for
?/forEach
?/rand
?/hmm
?/socket.io
?/27017
?/label
?/line

# Expression History (newest to oldest):

# Input Line History (newest to oldest):
@nodefest
@/usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/stage
@hatena
@はてダ下書き
@MESH_メモ
@y
@test3
@test2
@test
@Test
@n
@hecomi
@node-julius
@寝ます…
@kるか
@アレ作ってるけど割りと作業感出てきた
@ssdp たたいて iRemocon 発見できるように出来ないかなー
@net.createConnection でいけそうだ。
@Node.js に TCP/IP でメッセージ送れるヤツあるかな。
@TL からピザの匂いがしてきた…

# Input Line History (newest to oldest):

# Registers:
"0	LINE	0
			if (socket !== null) {
				socket.emit('result', {
					str: result
				});
			}
""1	LINE	0
			console.log('hogehoge');
"2	CHAR	0
	result
"3	CHAR	0
	str
"4	CHAR	0
	result
"5	CHAR	0
	 
"6	CHAR	0
	;
"7	CHAR	0
	esult
"8	CHAR	0
	str
"9	CHAR	0
	result
"j	CHAR	0
	JJJJJJJKJJJJJJJ/power./g�kbfgnnnnnnnnnnnnnnnnnnnKKKK:messages:echo string(�kb�kb�kb�kb�kb�kb�kb�kb high�kb�kb�kb�kb�kb�kb�kb�kb�ku�ku�kd�kd�kbm�ku:echo hi['gui']
"k	CHAR	0
	k
"q	CHAR	0
	j
"-	CHAR	0
	result

# File marks:
'0  1  3  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/recog.js
'1  1  0  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/p
'2  60  0  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/[quickrun output]
'3  6  0  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/main.js
'4  30  27  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/recog.js
'5  11  34  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/recog.js
'6  1  0  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/hoge.js
'7  5  24  ~/Dropbox/Program/javascript/node.js/tmp/binding.gyp
'8  1  0  ~/Dropbox/Program/javascript/node.js/tmp/hoge.cpp
'9  5  0  ~/Dropbox/Program/javascript/node.js/tmp/hoge.cpp

# Jumplist (newest first):
-'  1  3  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/recog.js
-'  7  0  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/recog.js
-'  9  0  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/recog.js
-'  55  0  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/recog.js
-'  1  0  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/p
-'  60  0  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/[quickrun output]
-'  61  0  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/[quickrun output]
-'  1  0  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/[quickrun output]
-'  1  0  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/split
-'  6  0  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/main.js
-'  1  0  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/main.js
-'  52  2  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/main.js
-'  112  1  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/main.js
-'  98  1  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/main.js
-'  44  1  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/recog.js
-'  45  3  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/recog.js
-'  40  12  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/recog.js
-'  43  5  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/recog.js
-'  33  2  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/recog.js
-'  46  12  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/recog.js
-'  48  0  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/recog.js
-'  32  2  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/recog.js
-'  27  16  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/recog.js
-'  11  0  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/recog.js
-'  30  15  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/recog.js
-'  8  0  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/recog.js
-'  51  0  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/recog.js
-'  1  0  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/hoge.js
-'  5  24  ~/Dropbox/Program/javascript/node.js/tmp/binding.gyp
-'  1  0  ~/Dropbox/Program/javascript/node.js/tmp/binding.gyp
-'  1  0  ~/Dropbox/Program/javascript/node.js/tmp/hoge.cpp
-'  8  0  ~/Dropbox/Program/javascript/node.js/tmp/binding.gyp
-'  5  0  ~/Dropbox/Program/javascript/node.js/tmp/hoge.cpp
-'  10  0  ~/Dropbox/Program/javascript/node.js/tmp/hoge.cpp
-'  13  0  ~/Dropbox/Program/javascript/node.js/tmp/hoge.cpp
-'  42  1  ~/Dropbox/Program/javascript/node.js/julius/src/julius.cpp
-'  1  0  ~/Dropbox/Program/javascript/node.js/julius/src/julius.cpp
-'  3  0  *unite* - vimfiler/history
-'  1  0  *unite* - vimfiler/history
-'  3  0  ~/Dropbox/Program/javascript/node.js/julius
-'  1  0  ~/Dropbox/Program/javascript/node.js/julius
-'  21  2  ~/Dropbox/Program/javascript/node.js/julius/*vimshell* - default
-'  7  0  ~/Dropbox/Program/javascript/node.js/julius/*vimfiler* - default
-'  1  0  ~/Dropbox/Program/javascript/node.js/julius/*vimfiler* - default
-'  24  18  ~/Dropbox/Program/javascript/node.js/julius/test2.js
-'  8  0  ~/Dropbox/Program/javascript/node.js/julius/test2.js
-'  1  0  ~/Dropbox/Program/javascript/node.js/julius/test2.js
-'  6  71  ~/Dropbox/Program/javascript/node.js/openjtalk/openjtalk.js
-'  1  0  ~/Dropbox/Program/javascript/node.js/openjtalk/openjtalk.js
-'  333  0  ~/Dropbox/Program/javascript/node.js/openjtalk/src/openjtalk.cpp
-'  257  5  ~/Dropbox/Program/javascript/node.js/openjtalk/src/openjtalk.cpp
-'  256  15  ~/Dropbox/Program/javascript/node.js/openjtalk/src/openjtalk.cpp
-'  330  1  ~/Dropbox/Program/javascript/node.js/openjtalk/src/openjtalk.cpp
-'  132  1  ~/Dropbox/Program/javascript/node.js/openjtalk/src/openjtalk.cpp
-'  1  0  ~/Dropbox/Program/javascript/node.js/openjtalk/src/openjtalk.cpp
-'  138  0  ~/.zshrc
-'  120  0  ~/.zshrc
-'  116  0  ~/.zshrc
-'  115  0  ~/.zshrc
-'  114  0  ~/.zshrc
-'  113  0  ~/.zshrc
-'  112  0  ~/.zshrc
-'  111  0  ~/.zshrc
-'  110  0  ~/.zshrc
-'  109  0  ~/.zshrc
-'  108  0  ~/.zshrc
-'  107  0  ~/.zshrc
-'  106  0  ~/.zshrc
-'  105  0  ~/.zshrc
-'  104  0  ~/.zshrc
-'  103  0  ~/.zshrc
-'  102  0  ~/.zshrc
-'  101  0  ~/.zshrc
-'  100  0  ~/.zshrc
-'  85  19  ~/.zshrc
-'  70  17  ~/.zshrc
-'  69  57  ~/.zshrc
-'  1  0  ~/.zshrc
-'  144  73  ~/.zshrc
-'  277  1  ~/Dropbox/Program/javascript/node.js/openjtalk/src/openjtalk.cpp
-'  1  0  ~/Dropbox/Program/javascript/node.js/openjtalk/text_to_speech.cpp
-'  1  0  ~/Dropbox/Program/javascript/node.js/openjtalk/text_to_speech.
-'  32  0  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/main.js
-'  11  142  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/*vimfiler* - default
-'  30  20  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/main.js
-'  114  1  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/main.js
-'  116  36  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/main.js
-'  25  19  ~/.earthquake/config
-'  1  0  ~/.earthquake/config
-'  1  0  /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/p

# History of marks within files (newest to oldest):

> /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/*unite* - default
	"	3	0
	.	3	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	395	0
	+	1	0
	+	394	0
	+	390	0
	+	9	0
	+	29	0
	+	49	0
	+	69	0
	+	89	0
	+	109	0
	+	129	0
	+	149	0
	+	169	0
	+	189	0
	+	209	0
	+	229	0
	+	249	0
	+	269	0
	+	289	0
	+	309	0
	+	329	0
	+	349	0
	+	369	0
	+	6	0
	+	3	0

> /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/recog.js
	"	1	3
	^	55	2
	.	9	0
	+	6	0
	+	6	16
	+	33	0
	+	22	0
	+	33	0
	+	47	0
	+	46	0
	+	47	0
	+	52	0
	+	31	0
	+	52	0
	+	52	0
	+	48	10
	+	6	9
	+	48	11
	+	47	38
	+	51	0
	+	52	0
	+	27	24
	+	28	0
	+	29	0
	+	30	0
	+	25	0
	+	51	3
	+	8	25
	+	8	0
	+	20	0
	+	20	0
	+	8	37
	+	20	0
	+	8	0
	+	20	0
	+	19	0
	+	24	15
	+	24	0
	+	29	0
	+	8	0
	+	8	25
	+	8	51
	+	8	22
	+	8	0
	+	23	0
	+	8	7
	+	8	16
	+	8	23
	+	4	17
	+	6	0
	+	8	39
	+	8	1
	+	8	30
	+	8	0
	+	30	6
	+	29	19
	+	30	0
	+	1	0
	+	8	0
	+	30	23
	+	8	0
	+	8	0
	+	13	0
	+	12	6
	+	11	0
	+	7	24
	+	30	62
	+	11	34
	+	30	27
	+	11	0
	+	9	34
	+	12	54
	+	30	8
	+	27	0
	+	25	35
	+	27	69
	+	26	0
	+	30	15
	+	26	0
	+	30	14
	+	11	0
	+	10	0
	+	10	0
	+	27	0
	+	27	0
	+	27	33
	+	27	2
	+	27	0
	+	46	0
	+	46	0
	+	46	0
	+	45	2
	+	34	0
	+	39	0
	+	45	0
	+	40	0
	+	45	0
	+	35	21
	+	36	9
	+	41	21
	+	42	0
	+	55	0
	+	9	0

> /usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/socket.io/*vimshell* - default@1
	"	2	0
	^	2	0
	.	1	2
	+	1	2
