# This viminfo file was generated by Vim 7.2.
# You may edit it if you're careful!

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~h
# Last Search Pattern:
~MSle0~/reani

# Last Substitute Search Pattern:
~MSle0&

# Last Substitute String:
$

# Command Line History (newest to oldest):
:q
:w
:cd $HOME
:NeoBundleInstall
:NeoBundleIn
:wq
:NeoBundleClean
:q!
:%s///ge
:%s/^M//g
:qa
:set nonumber
:Unite boost-online-doc
:NeoBundle
:boost-
:Unite -a
:set paste
:NeoBundleClear
:e fusion.cpp
:k

# Search String History (newest to oldest):
? \s\+$
?/reani
?/reanim
? 
? ^M
?/character
?/default
?/mysqld
?/default-character
??i<?iaaa:q
?/boost-
?/NeoBun
?/NeoBundle
?/tlib
? +$
?/error
? <\\n>
? ascii
? wstring
? L"

# Expression History (newest to oldest):
====================================================================================================

# Input Line History (newest to oldest):
@vimrc
@ã‚³ãƒ¼ãƒ’ãƒ¼é£²ã¿ãŸã„
@y

# Input Line History (newest to oldest):

# Registers:
"0	LINE	0
	================================================================
"1	CHAR	0
	 -dump %s'
	endif
	" alc
	" ---------------------------------------------------------------------------------------------------
	nmap ,ra :<C-u>Ref alc<Space>
"2	LINE	0
	
"3	LINE	0
	[[ -s "/home/hecomi/.rvm/scripts/rvm" ]] && source "/home/hecomi/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
"4	LINE	0
	ã‚³ãƒãƒ³ãƒ‰ã‚’æ›¸ã„ãŸ XML:
"5	LINE	0
	ä¾‹ï¼š
"6	LINE	0
	ã‹ã‚‰ã€grammar & voca ã‚’ç”Ÿæˆã€mkdfa.pl ã«é£Ÿã‚ã›ã‚‹ã¨ dfa & dict ã‚’åãå‡ºã™ã€‚
	ã¨ã„ã†ã¨ã“ã‚ã‚’å…¨éƒ¨
"7	LINE	0
	<VirtualHost *:10080>
		ServerName hecomix
		DocumentRoot /usr/share/redmine/public
	</VirtualHost>
"8	LINE	0
		ServerName [ã‚µãƒ¼ãƒå]
"9	LINE	0
		str.extract(0, length, latin, "utf8");
"d	CHAR	0
	1269
<dddkkkkkkkkkkkkkkkkkkjjjjjjjjjjjjjjjjjjjkjjjjjjjjjjjjjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkkhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxiir_sendlllllllllllllllllllllxxxxinum	€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb int num	€kb€kb€kb€kb€kb€kbnumj€kbjjjjjjjjjkddddVjjjdjlllllllllllllllllhhxxxkkkkkkkkkkkkkkkkkhhhhhhhhhhhhhhhhhhhhxxxxxxxxxx€kblllllllhhhhhhi€kb ljhhhhhhhhhhhhhhhhhhhhhhhi€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kbtlxxxxxxxxxxxxxxxxxxxxxxxxxxxxjjkkkkkkddddjhhi_jjjjjjjjjjjjjkVjjjdkkkkkkpkddkkkkkkoip::tcp::io	 s_;jjjjjjkkjjjjjllli_hhhhhhhhhhhhhhhhhhhxxxxxxxxxxxxxxxxxxxxxxxxxas.\€kb€kb_.€kb..€kb€kb.connect(ep);jjjjjjjkddjostd::cout << "€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb€kb::string cmd = "*is;" + num + "\r\n";jhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhxxxxxxxxxxxxxxxxxxxxxxxicmdkoc€kbstd;;:c€kb€kb€kb€kb::cout << cmd << std::endl;€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kl€kr€kr€kr€kr€kr€kr"COMMAND: " << €kl€kl€kl€kl€kl€kl€kl€#4€#4€#4€kr€kr€kr€krxxxhhxdwiIRjkhlliEMOCONj:q€kbwkkkkkkkkkkkkkkkkkjjjjjjjjo~iRe	(){}ka		s?€kb_.close();jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjkkVjjjjjjjjjjjjjjkkjdddjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkVjjjjjjjjjjjjjjjjjjjjjjjjjjkkkjdiwuuVjjjjjjjjjjjjjjjjjjjjjgiwkkkkjj
"j	CHAR	0
	jkuuujjjko>>a€kb lit("q€kb|)"(€kb) [phx::push_back(phx::ref(buf)m,€kb€kb, "":€kb]:w\r:qhhhhhlllla):w\r
"k@	CHAR	0
	jk
"q	CHAR	0
	:qkkk
"r	CHAR	0
	jjjjkkk
"x	CHAR	0
	xxx€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€kr€krxxxx;w
""-	CHAR	0
	M

# File marks:
'0  1  0  ~/.vimrc
'1  524  40  ~/.vimrc
'2  2  0  ~/.vimrc
'3  211  0  ~/.vimrc
'4  185  45  ~/.vimrc
'5  537  0  ~/.vimrc
'6  500  0  ~/.vimrc
'7  109  0  ~/.bashrc
'8  1  0  /etc/mediatomb/config.xml
'9  108  0  ~/.bashrc

# Jumplist (newest first):
-'  1  0  ~/.vimrc
-'  524  40  ~/.vimrc
-'  250  41  ~/.vimrc
-'  256  0  ~/.vimrc
-'  2  0  ~/.vimrc
-'  211  0  ~/.vimrc
-'  185  45  ~/.vimrc
-'  522  6  ~/.vimrc
-'  80  0  ~/.vimrc
-'  122  0  ~/.vimrc
-'  537  0  ~/.vimrc
-'  500  0  ~/.vimrc
-'  516  0  ~/.vimrc
-'  109  0  ~/.bashrc
-'  42  0  ~/.bashrc
-'  1  0  ~/.bashrc
-'  1  0  /etc/mediatomb/config.xml
-'  108  0  ~/.bashrc
-'  24  63  ~/.profile
-'  1  0  ~/.profile
-'  25  129  ~/.profile
-'  29  169  ~/Dropbox/Program/cpp/julius/mk_gram_voca/README
-'  30  0  ~/Dropbox/Program/cpp/julius/mk_gram_voca/README
-'  1  0  ~/Dropbox/Program/cpp/julius/mk_gram_voca/README
-'  7  0  /etc/mysql/my.cnf
-'  115  34  /etc/mysql/my.cnf
-'  10  10  /etc/mysql/my.cnf
-'  99  23  /etc/mysql/my.cnf
-'  50  33  /etc/mysql/my.cnf
-'  41  0  /etc/mysql/my.cnf
-'  3  0  /etc/mysql/my.cnf
-'  1  0  /etc/mysql/my.cnf
-'  21  0  /etc/mysql/my.cnf
-'  4  30  /etc/apache2/mods-available/passenger.conf
-'  1  0  /etc/apache2/mods-available/passenger.conf
-'  44  3  /etc/apache2/sites-enabled/000-default
-'  1  0  /etc/apache2/sites-enabled/000-default
-'  2  0  /etc/apache2/sites-enabled/000-default
-'  5  5  /etc/apache2/sites-enabled/000-default
-'  46  3  /etc/apache2/sites-enabled/000-default
-'  44  0  /etc/apache2/sites-available/default
-'  1  0  /etc/apache2/sites-available/default
-'  43  0  /etc/apache2/sites-available/default
-'  45  1  /etc/apache2/sites-available/default
-'  1  0  ~/Dropbox/Program/php/tmp/utf8encode.php
-'  2  12  ~/Dropbox/Program/php/tmp/utf8encode.php
-'  3  1  ~/Dropbox/Program/php/tmp/utf8encode.php
-'  40  63  ~/Dropbox/Program/cpp/mecab/test/kanji2kana_2.cpp
-'  1  0  ~/Dropbox/Program/cpp/mecab/test/kanji2kana_2.cpp
-'  45  18  ~/Dropbox/Program/cpp/mecab/test/kanji2kana_2.cpp
-'  32  48  ~/Dropbox/Program/cpp/mecab/test/kanji2kana_2.cpp
-'  107  6  ~/Dropbox/Program/cpp/mecab/test/kanji2kana_2.cpp
-'  24  12  ~/Dropbox/Program/cpp/mecab/test/kanji2kana_2.cpp
-'  59  2  ~/Dropbox/Program/cpp/mecab/test/kanji2kana_2.cpp
-'  39  7  ~/Dropbox/Program/cpp/mecab/test/kanji2kana_2.cpp
-'  53  0  ~/Dropbox/Program/cpp/mecab/test/kanji2kana_2.cpp
-'  43  0  ~/Dropbox/Program/cpp/mecab/test/kanji2kana_2.cpp
-'  27  5  ~/Dropbox/Program/cpp/mecab/test/kanji2kana_2.cpp
-'  50  19  ~/Dropbox/Program/cpp/mecab/test/kanji2kana_2.cpp
-'  41  0  ~/Dropbox/Program/cpp/mecab/test/kanji2kana_2.cpp
-'  49  10  ~/Dropbox/Program/cpp/mecab/test/kanji2kana_2.cpp
-'  44  0  ~/Dropbox/Program/cpp/mecab/test/kanji2kana_2.cpp
-'  56  7  ~/Dropbox/Program/cpp/mecab/test/kanji2kana_2.cpp
-'  42  3  ~/Dropbox/Program/cpp/mecab/test/kanji2kana_2.cpp
-'  54  26  ~/Dropbox/Program/cpp/mecab/test/kanji2kana_2.cpp
-'  101  73  ~/Dropbox/Program/cpp/mecab/test/kanji2kana_2.cpp
-'  5  0  ~/Dropbox/Program/cpp/boost/range/adaptors/reversed.cpp
-'  9  0  ~/Dropbox/Program/cpp/boost/range/adaptors/reversed.cpp
-'  1  0  ~/Dropbox/Program/cpp/boost/range/adaptors/reversed.cpp
-'  13  67  ~/Dropbox/Program/cpp/boost/range/adaptors/reversed.cpp
-'  6  0  ~/Dropbox/Program/cpp/boost/range/adaptors/reversed.cpp
-'  11  0  ~/Dropbox/Program/cpp/boost/range/adaptors/reversed.cpp
-'  6  30  ~/Dropbox/Program/cpp/iRemocon/main.cpp
-'  1  0  ~/Dropbox/Program/cpp/iRemocon/main.cpp
-'  1  0  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/unite-boost-online-doc/autoload/unite/sources/test.vim
-'  182  0  ~/.vimrc
-'  181  45  ~/.vimrc
-'  45  38  ~/Dropbox/Program/cpp/mecab/test/fusion.cpp
-'  1  0  ~/Dropbox/Program/cpp/mecab/test/test2.cpp
-'  47  1  ~/Dropbox/Program/cpp/mecab/test/fusion.cpp
-'  16  54  ~/Dropbox/Program/cpp/mecab/test/fusion.cpp
-'  24  0  ~/Dropbox/Program/cpp/mecab/test/fusion.cpp
-'  48  0  ~/Dropbox/Program/cpp/mecab/test/fusion.cpp
-'  49  22  ~/Dropbox/Program/cpp/mecab/test/fusion.cpp
-'  51  0  ~/Dropbox/Program/cpp/mecab/test/fusion.cpp
-'  21  20  ~/Dropbox/Program/cpp/mecab/test/fusion.cpp
-'  13  0  ~/Dropbox/Program/cpp/mecab/test/fusion.cpp
-'  18  16  ~/Dropbox/Program/cpp/mecab/test/fusion.cpp
-'  11  37  ~/Dropbox/Program/cpp/mecab/test/fusion.cpp
-'  26  0  ~/Dropbox/Program/cpp/mecab/test/fusion.cpp

# History of marks within files (newest to oldest):

> ~/.vimrc
	"	1	0
	^	524	41
	.	524	40
	+	574	0
	+	517	32
	+	517	32
	+	572	0
	+	574	0
	+	575	0
	+	573	0
	+	1	1
	+	1	0
	+	1	0
	+	1	5
	+	1	0
	+	1	10
	+	1	0
	+	1	64
	+	1	0
	+	1	26
	+	1	0
	+	1	1
	+	1	0
	+	1	20
	+	1	29
	+	1	0
	+	1	0
	+	1	18
	+	1	0
	+	1	0
	+	1	37
	+	1	0
	+	1	0
	+	1	35
	+	1	24
	+	1	32
	+	1	26
	+	1	0
	+	1	0
	+	1	32
	+	1	0
	+	1	10
	+	1	0
	+	1	52
	+	1	0
	+	1	0
	+	1	12
	+	1	0
	+	515	31
	+	181	11
	+	1	0
	+	185	0
	+	250	41
	+	252	0
	+	524	40

> ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/*unite* - default@1
	"	3	0
	.	3	0
	+	1	0
	+	5	0
	+	3	0
