# This viminfo file was generated by Vim 7.3.
# You may edit it if you're careful!

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~h
# Last Search Pattern:
~MSle0~/path

# Last Substitute Search Pattern:
~MSle0&4.2.1

# Last Substitute String:
$

# Command Line History (newest to oldest):
:wq
:w
:q
:e ../../binding.gyp
:e julius.hpp
:/::Close
:%S/JavaScript/ JavaScript/c
:%S/コールバック呼び出し/JavaScript 側のコールバック呼び出し/c
:%S/処理/コールバック呼び出し/c
:80
:qa!
:qa
:echo LIBRARY_OPTIONS
:echo NODE_INCLUDE_PATH
:echo system('node -v')[1:-2]
:echo system('node -v')[1:-3]
:echo len(system('node -v'))
:echo system('node -v')[1:5]
:echo system('node -v')[1:4]
:echo system('node -v')[1:2]

# Search String History (newest to oldest):
? \s\+$
?/path
?/hoge
?/result[
?/result
?/resu;t
?/12
?/n
?/num
?/Tagger
?/make
?/tagger
?/getInstance
?/lib
?/mecab
?/exec
?/jconf
?/init
?/const
?/destru

# Expression History (newest to oldest):

# Input Line History (newest to oldest):
@y
@test3
@test2
@test
@Test
@n
@hecomi
@node-julius
@寝ます…
@kるか
@アレ作ってるけど割りと作業感出てきた
@ssdp たたいて iRemocon 発見できるように出来ないかなー
@net.createConnection でいけそうだ。
@Node.js に TCP/IP でメッセージ送れるヤツあるかな。
@TL からピザの匂いがしてきた…
@うどん煮こむか
@風吹いてきた
@3 時くらいに昼飯食べたけどもうお腹すいてきた…
@あー、やっと直った…、時間浪費した…。
@あぁ、http と https 自動で割り振ってくれるのか。

# Input Line History (newest to oldest):

# Registers:
"0	LINE	0
	
	class MeCabTagger : private boost::noncopyable
	{
	public:
		static MeCab::Tagger* getInstance() {
			static MeCab::Tagger *tagger = MeCab::createTagger("");
			return tagger;
		}
	};
	
"1	CHAR	0
	;
"2	LINE	0
		std::shared_ptr<
"3	LINE	0
		std::cout << *str << std::endl;
"4	LINE	0
	
	class MeCabTagger : private boost::noncopyable
	{
	public:
		static MeCab::Tagger* getInstance() {
			static MeCab::Tagger *tagger = MeCab::createTagger("");
			return tagger;
		}
	};
	
"5	LINE	0
	#include <boost/noncopyable.hpp>
"6	LINE	0
		std::cout << "hoge" << std::endl;
"7	LINE	0
		std::cout << "hoge" << std::endl;
"8	LINE	0
	                    'library_dirs' : [
	                        '/usr/local/lib',
	                    ],
"9	CHAR	0
	include/libcxx
"j	CHAR	0
	JJJJJJJKJJJJJJJ/power./g�kbfgnnnnnnnnnnnnnnnnnnnKKKK:messages:echo string(�kb�kb�kb�kb�kb�kb�kb�kb high�kb�kb�kb�kb�kb�kb�kb�kb�ku�ku�kd�kd�kbm�ku:echo hi['gui']
"k	CHAR	0
	k
"q	CHAR	0
	j
""-	CHAR	0
	;

# File marks:
'0  29  1  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/mecab.cc
'1  235  36  ~/.vimrc
'2  31  1  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/mecab.cc
'3  14  0  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/wscript
'4  1  0  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/mecab.cc
'5  8  20  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/binding.gyp
'6  15  21  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/binding.gyp
'7  12  58  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/wscript
'8  11  18  ~/Dropbox/Program/cpp/mecab/test/test2.cpp
'9  3  0  ~/Dropbox/Program/cpp/mecab/test/test2.cpp

# Jumplist (newest first):
-'  29  1  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/mecab.cc
-'  2  18  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/mecab.cc
-'  1  0  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/mecab.cc
-'  235  36  ~/.vimrc
-'  1  0  ~/.vimrc
-'  30  1  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/mecab.cc
-'  46  0  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/mecab.cc
-'  31  1  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/mecab.cc
-'  14  0  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/wscript
-'  1  0  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/wscript
-'  8  20  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/binding.gyp
-'  1  0  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/binding.gyp
-'  15  21  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/binding.gyp
-'  12  58  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/wscript
-'  11  18  ~/Dropbox/Program/cpp/mecab/test/test2.cpp
-'  1  0  ~/Dropbox/Program/cpp/mecab/test/test2.cpp
-'  3  0  ~/Dropbox/Program/cpp/mecab/test/test2.cpp
-'  17  1  ~/Dropbox/Program/cpp/mecab/test/test.cpp
-'  1  0  ~/Dropbox/Program/cpp/mecab/test/test.cpp
-'  11  0  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/export_to_nodejs.cpp
-'  1  0  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/export_to_nodejs.cpp
-'  24  2  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/mecab.cc
-'  11  32  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/wscript
-'  18  25  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/wscript
-'  20  0  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/mecab.cc
-'  52  1  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/mecab.cc
-'  5  22  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/mecab.js
-'  1  0  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/mecab.js
-'  10  23  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/binding.gyp
-'  50  40  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/mecab.cc
-'  42  6  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/mecab.cc
-'  33  33  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/mecab.cc
-'  12  2  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/mecab.cc
-'  64  0  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/mecab.cc
-'  3  0  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/mecab.cc
-'  5  16  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/mecab.cc
-'  56  28  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/mecab.cc
-'  4  33  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/binding.gyp
-'  12  30  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/binding.gyp
-'  39  5  ~/Dropbox/Program/javascript/node.js/julius/binding.gyp
-'  4  3  ~/Dropbox/Program/javascript/node.js/julius/binding.gyp
-'  1  0  ~/Dropbox/Program/javascript/node.js/julius/binding.gyp
-'  3  0  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/binding.gyp
-'  5  35  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/binding.gyp
-'  3  0  ~/Dropbox/Program/javascript/node.js/julius/node_modules/juliusData
-'  1  0  ~/Dropbox/Program/javascript/node.js/julius/node_modules/juliusData
-'  26  22  ~/Dropbox/Program/cpp/node/HAS/node_addon/juliusData/juliusData.js
-'  6  4  ~/Dropbox/Program/cpp/node/HAS/node_addon/juliusData/juliusData.js
-'  335  16  ~/Dropbox/Program/cpp/node/HAS/node_addon/juliusData/juliusData.js
-'  7  60  ~/Dropbox/Program/cpp/node/HAS/node_addon/juliusData/juliusData.js
-'  268  5  ~/Dropbox/Program/cpp/node/HAS/node_addon/juliusData/juliusData.js
-'  1  0  ~/Dropbox/Program/cpp/node/HAS/node_addon/juliusData/juliusData.js
-'  54  19  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  44  0  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  165  2  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  164  2  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  158  37  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  153  9  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  149  0  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  51  29  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  50  19  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  1  0  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  3  0  ~/Dropbox/Program/javascript/node.js/julius/setting.jconf
-'  1  0  ~/Dropbox/Program/javascript/node.js/julius/setting.jconf
-'  1  0  ~/Dropbox/Program/javascript/node.js/julius/model/phone_m/hmmdefs_monof_mix16_gid.binhmm
-'  271  22  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  262  16  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  223  12  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  221  23  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  138  0  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  37  0  ~/Dropbox/Program/javascript/node.js/julius/test.js
-'  1  0  ~/Dropbox/Program/javascript/node.js/julius/test.js
-'  147  0  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  152  60  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  70  1  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  108  20  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  103  13  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  98  8  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  79  10  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  69  18  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  68  18  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  19  7  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  18  3  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  12  8  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  285  3  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  217  12  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  211  9  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  205  9  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  199  9  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  186  2  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  180  2  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  172  2  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  3  0  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  24  11  ~/Dropbox/Program/javascript/node.js/julius/test.js
-'  21  11  ~/Dropbox/Program/javascript/node.js/julius/test.js
-'  17  11  ~/Dropbox/Program/javascript/node.js/julius/test.js
-'  14  0  ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/wscript

# History of marks within files (newest to oldest):

> ~/Dropbox/Program/javascript/node.js/julius/node_modules/mecab/mecab.cc
	"	29	1
	.	2	0
	+	12	0
	+	12	0
	+	12	16
	+	12	26
	+	12	0
	+	12	0
	+	12	0
	+	12	0
	+	12	0
	+	3	0
	+	31	23
	+	56	0
	+	60	40
	+	61	0
	+	12	0
	+	4	16
	+	31	0
	+	12	0
	+	4	0
	+	1	0
	+	31	73
	+	12	0
	+	40	28
	+	41	52
	+	40	21
	+	60	0
	+	31	34
	+	30	65
	+	31	10
	+	33	34
	+	10	40
	+	9	43
	+	38	60
	+	2	16
	+	33	0
	+	33	33
	+	33	0
	+	44	31
	+	38	25
	+	45	0
	+	35	0
	+	33	0
	+	34	0
	+	33	0
	+	48	48
	+	49	0
	+	34	36
	+	44	11
	+	48	44
	+	53	0
	+	50	40
	+	51	0
	+	53	0
	+	52	0
	+	50	40
	+	20	33
	+	28	0
	+	32	0
	+	46	0
	+	52	0
	+	20	0
	+	20	0
	+	28	0
	+	31	0
	+	30	0
	+	31	0
	+	32	0
	+	20	0
	+	24	17
	+	25	33
	+	22	5
	+	37	84
	+	31	31
	+	30	4
	+	12	0
	+	12	0
	+	3	31
	+	30	41
	+	46	0
	+	52	0
	+	3	0
	+	12	0
	+	11	0
	+	31	0
	+	30	0
	+	2	0
