# This viminfo file was generated by Vim 7.3.
# You may edit it if you're careful!

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~h
# Last Search Pattern:
~MSle0~/mecab_new

# Last Substitute Search Pattern:
~MSle0&4.2.1

# Last Substitute String:
$

# Command Line History (newest to oldest):
:q
:w
:wq
:e julius.js
:e test/test.js
:e node_modules/mecab-async/build/
:q!
:!node-gyp configure build
:e node_modules/openjtalk/openjtalk.js
:e views/devices.ejs
:%S/}}}/\/\/ }}}/
:%S/{{{/\/\/ {{{/
:2
:e ..
:!npm install
:e ../julius/package.json
:e node_modules/
:'<,'>S/\((.*?)\)/ : \1/
:'<,'>S/(\(.*?\))/ : \1/
:e src/openjtalk.hpp

# Search String History (newest to oldest):
? \s\+$
?/mecab_new
?/hoge
?/printf
?/open
?/4ok
?/4
?/LA
?/LAX
?/extern
?/mecab2njd
?/lib
? \<Mecab_load\>
?/load
?/make_wav
?/err
?/talk
?/hogehoge
?/port
?/hmm

# Expression History (newest to oldest):

# Input Line History (newest to oldest):
@nodefest
@/usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/stage
@hatena
@はてダ下書き
@MESH_メモ
@y
@test3
@test2
@test
@Test
@n
@hecomi
@node-julius
@寝ます…
@kるか
@アレ作ってるけど割りと作業感出てきた
@ssdp たたいて iRemocon 発見できるように出来ないかなー
@net.createConnection でいけそうだ。
@Node.js に TCP/IP でメッセージ送れるヤツあるかな。
@TL からピザの匂いがしてきた…

# Input Line History (newest to oldest):

# Registers:
"0	CHAR	0
	.RTLD_LOCAL
"1	CHAR	0
	.RTLD_LOCAL
"2	CHAR	0
	LOCAL
"3	LINE	0
	  printf("hoge");
"4	LINE	0
		if (&open_jtalk_data_.mecab == NULL) std::cout << "NULL" << std::endl;
		std::cout << "4ok" << std::endl;
"5	CHAR	0
	4
"6	LINE	0
	var OpenJTalk = require('openjtalk');
	var tts = new OpenJTalk();
	tts.talk('こんにちは');
	
"7	CHAR	0
	LAZY
"8	CHAR	0
	GLOBAL
"9	CHAR	0
	:
"j	CHAR	0
	JJJJJJJKJJJJJJJ/power./g�kbfgnnnnnnnnnnnnnnnnnnnKKKK:messages:echo string(�kb�kb�kb�kb�kb�kb�kb�kb high�kb�kb�kb�kb�kb�kb�kb�kb�ku�ku�kd�kd�kbm�ku:echo hi['gui']
"k	CHAR	0
	k
"q	CHAR	0
	j
""-	CHAR	0
	.RTLD_LOCAL

# File marks:
'0  16  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/test.js
'1  3  22  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/test.js
'2  60  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/lib/open_jtalk-1.05/mecab/src/mecab.cpp
'3  76  2  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/lib/open_jtalk-1.05/mecab/src/mecab.cpp
'4  235  1  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
'5  12  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/test.js
'6  4  34  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/test.js
'7  2  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/openjtalk.js
'8  6  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/test.js
'9  6  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/test.js

# Jumplist (newest first):
-'  16  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/test.js
-'  2  13  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/test.js
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/test.js
-'  3  22  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/test.js
-'  60  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/lib/open_jtalk-1.05/mecab/src/mecab.cpp
-'  78  13  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/lib/open_jtalk-1.05/mecab/src/mecab.cpp
-'  76  2  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/lib/open_jtalk-1.05/mecab/src/mecab.cpp
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/lib/open_jtalk-1.05/mecab/src/mecab.cpp
-'  11  20  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/lib/open_jtalk-1.05/mecab/src/mecab.cpp
-'  9  38  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/lib/open_jtalk-1.05/mecab/src/mecab.cpp
-'  80  61  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/lib/open_jtalk-1.05/mecab/src/mecab.cpp
-'  235  1  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  379  15  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  234  15  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  22  28  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  12  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/test.js
-'  4  34  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/test.js
-'  5  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/test.js
-'  6  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/test.js
-'  2  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/openjtalk.js
-'  3  38  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/openjtalk.js
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/openjtalk.js
-'  8  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/test.js
-'  18  3  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/test.js
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/[quickrun output]
-'  14  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/[quickrun output]
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/split
-'  7  20  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/test.js
-'  6  34  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/test.js
-'  1  2  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/test.js
-'  4  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/julius.js
-'  10  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/JuliusGrammar.js
-'  13  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/test.js
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/test/test.js
-'  2  0  ~/Dropbox/Program/javascript/node.js/has/test2.js
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/test2.js
-'  11  42  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/julius.js
-'  9  1  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/julius.js
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/julius.js
-'  10  46  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/openjtalk.js
-'  12  48  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/openjtalk.js
-'  24  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/openjtalk.js
-'  5  73  ~/Dropbox/Program/javascript/node.js/has/test.js
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/test.js
-'  2  0  ~/Dropbox/Program/javascript/node.js/has/test.js
-'  27  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/src/julius.cpp
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/src/julius.cpp
-'  494  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  276  1  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  12  10  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  272  1  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  24  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  4  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/lib/open_jtalk-1.05/mecab/src
-'  3  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/lib/open_jtalk-1.05/mecab/src
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/lib/open_jtalk-1.05/mecab/src
-'  479  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  29  4  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/binding.gyp
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/binding.gyp
-'  57  5  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/binding.gyp
-'  58  5  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/binding.gyp
-'  51  5  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/binding.gyp
-'  386  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  481  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  300  16  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  480  1  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  156  32  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  155  27  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  150  21  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  157  3  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  125  1  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  9  0  ~/Dropbox/Program/javascript/node.js/has/test.js
-'  15  0  ~/Dropbox/Program/javascript/node.js/has/test.js
-'  64  37  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  5  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/Makefile
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/Makefile
-'  4  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/package.json
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/package.json
-'  33  0  ~/Dropbox/Program/javascript/node.js/has/test.js
-'  4  27  ~/Dropbox/Program/javascript/node.js/has/test.js
-'  1  0  src/openjtalk.cpp
-'  413  1  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  444  1  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  425  1  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  419  1  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  412  1  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  409  1  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  447  4  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  176  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/src/openjtalk.cpp
-'  26  30  ~/Dropbox/Program/javascript/node.js/has/test.js
-'  25  19  ~/Dropbox/Program/javascript/node.js/has/test.js
-'  24  15  ~/Dropbox/Program/javascript/node.js/has/test.js
-'  32  2  ~/Dropbox/Program/javascript/node.js/has/test.js
-'  8  0  ~/Dropbox/Program/javascript/node.js/has/test.js

# History of marks within files (newest to oldest):

> ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/test.js
	"	16	0
	^	3	23
	.	2	13
	+	6	0
	+	6	9
	+	8	0
	+	18	0
	+	9	0
	+	18	0
	+	9	5
	+	6	36
	+	6	25
	+	6	21
	+	6	27
	+	6	0
	+	6	0
	+	6	0
	+	6	0
	+	1	29
	+	1	0
	+	4	0
	+	4	0
	+	5	0
	+	4	34
	+	6	0
	+	13	0
	+	12	0
	+	2	25
	+	3	22
	+	2	13

> ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/split
	"	1	0

> ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/*unite* - quickrun-hook-unite-quickfix
	"	6	0
	.	3	0
	+	23	0
	+	16	0
	+	3	0
