# This viminfo file was generated by Vim 7.3.
# You may edit it if you're careful!

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~h
# Last Search Pattern:
~MSle0~/snippet

# Last Substitute Search Pattern:
~MSle0&j

# Last Substitute String:
$

# Command Line History (newest to oldest):
:q
:wq
:w
:h neosnippet
:e ../openjtalk/Makefile
:e kana2voca.js
:'<,'>S/$/,/
:'<,'>Alignta ,
:'<,'>%S
:%S/\tboost::algorithm::replace_all\(w , "(.*?)","(.*?)");/"\1", "\2"/
:%S/\tboost::algorithm::replaceall\(w , "(.*?)","(.*?)");/"\1", "\2"/
:set fileformat=vimrc
:qa
:e testApp.h
:%S/threshould/threshold/g
:grayImage
:e src/testApp.cpp
:s/j/i/g
:e twmidi.js
:e test.js

# Search String History (newest to oldest):
? \s\+$
?/snippet
?/e
?/C-e
?/expand
?/わ
?/を
?/toVoca
? $
? \tboost::algorithm::replace_all(w , "\(.\{-}\)","\(.\{-}\)");
? \tboost::algorithm::replaceall(w , "\(.\{-}\)","\(.\{-}\)");
?/Shift
?/findCon
?/mousePres
?/update
? threshould
?/grayImage
?/set
?/draw
? j

# Expression History (newest to oldest):

# Input Line History (newest to oldest):
@K
@nodefest
@/usr/local/Cellar/nginx/1.2.3/html/enchant.js/examples/plugins/gl/mmd/stage
@hatena
@はてダ下書き
@MESH_メモ
@y
@test3
@test2
@test
@Test
@n
@hecomi
@node-julius
@寝ます…
@kるか
@アレ作ってるけど割りと作業感出てきた
@ssdp たたいて iRemocon 発見できるように出来ないかなー
@net.createConnection でいけそうだ。
@Node.js に TCP/IP でメッセージ送れるヤツあるかな。

# Input Line History (newest to oldest):

# Registers:
""0	LINE	0
	nnoremap <silent> <S-j> <C-d>
	nnoremap <silent> <S-k> <C-u>
"1	CHAR	0
	C-e
"2	CHAR	0
	e
"3	CHAR	0
	x
"4	CHAR	0
	-
"5	CHAR	0
	C
"6	CHAR	0
	 
"7	CHAR	0
	w
"8	CHAR	0
	e
"9	LINE	0
		npm install
"j	CHAR	0
	JJJJJJJKJJJJJJJ/power./g�kbfgnnnnnnnnnnnnnnnnnnnKKKK:messages:echo string(�kb�kb�kb�kb�kb�kb�kb�kb high�kb�kb�kb�kb�kb�kb�kb�kb�ku�ku�kd�kd�kbm�ku:echo hi['gui']
"k	CHAR	0
	k
"q	CHAR	0
	j
"-	CHAR	0
	C-e

# File marks:
'0  2  0  ~/Dropbox/dotfiles/.vimrc
'1  1  0  ~/tmp/julius/node_modules/julius/JuliusGrammar.js
'2  1  0  ~/tmp/julius/node_modules/julius/main.cpp
'3  90  100  ~/.vimrc
'4  154  26  ~/.vimrc
'5  29  0  ~/tmp/julius/node_modules/julius/JuliusGrammar.js
'6  11  88  ~/tmp/julius/node_modules/julius/test/test.js
'7  7  0  ~/tmp/julius/node_modules/julius/test/test2.js
'8  4  0  ~/tmp/julius/node_modules/node-julius/package.json
'9  372  15  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/kana2voca.js

# Jumplist (newest first):
-'  2  0  ~/Dropbox/dotfiles/.vimrc
-'  1  0  ~/Dropbox/dotfiles/.vimrc
-'  1  0  ~/tmp/julius/node_modules/julius/JuliusGrammar.js
-'  1  0  ~/tmp/julius/node_modules/julius/main.cpp
-'  2  0  ~/tmp/julius/node_modules/julius/main.cpp
-'  90  100  ~/.vimrc
-'  1  0  ~/.vimrc
-'  154  26  ~/.vimrc
-'  548  34  ~/.vimrc
-'  275  21  ~/.vimrc
-'  856  0  ~/.vimrc
-'  126  0  ~/.vimrc
-'  127  3  ~/.vimrc
-'  117  0  ~/.vimrc
-'  29  0  ~/tmp/julius/node_modules/julius/JuliusGrammar.js
-'  48  1  ~/tmp/julius/node_modules/julius/JuliusGrammar.js
-'  11  88  ~/tmp/julius/node_modules/julius/test/test.js
-'  1  0  ~/tmp/julius/node_modules/julius/test/test.js
-'  7  0  ~/tmp/julius/node_modules/julius/test/test2.js
-'  1  0  ~/tmp/julius/node_modules/julius/test/test2.js
-'  4  0  ~/tmp/julius/node_modules/node-julius/package.json
-'  1  0  ~/tmp/julius/node_modules/node-julius/package.json
-'  372  15  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/kana2voca.js
-'  358  1  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/kana2voca.js
-'  54  10  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/kana2voca.js
-'  218  2  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/kana2voca.js
-'  55  1  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/kana2voca.js
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/kana2voca.js
-'  19  5  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/Makefile
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/Makefile
-'  15  1  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/Makefile
-'  18  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/package.json
-'  13  22  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/package.json
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/package.json
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/package.json
-'  4  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/Makefile
-'  4  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/openjtalk/package.json
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/README.md
-'  7  4  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/package.json
-'  3  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/README.md
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/README.md
-'  22  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/README.md
-'  1  1  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/[quickrun output]
-'  3  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/[quickrun output]
-'  2  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/[quickrun output]
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/split
-'  3  60  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/test.js
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/test.js
-'  2  30  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/kana2voca.js
-'  69  2  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/JuliusGrammar.js
-'  86  1  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/JuliusGrammar.js
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/JuliusGrammar.js
-'  3  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/kana2voca.js
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/*unite* - quickrun-hook-unite-quickfix
-'  8  18  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/package.json
-'  14  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/package.json
-'  13  2  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/package.json
-'  12  15  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/package.json
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/package.json
-'  16  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/README.md
-'  9  99  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/README.md
-'  3  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/package.json
-'  82  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/JuliusGrammar.js
-'  5  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/JuliusGrammar.js
-'  42  1  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/k2v.js
-'  98  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/k2v.js
-'  100  13  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/k2v.js
-'  391  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/k2v.js
-'  99  2  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/k2v.js
-'  101  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/k2v.js
-'  102  20  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/k2v.js
-'  16  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/k2v.js
-'  38  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/k2v.js
-'  15  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/k2v.js
-'  103  8  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/k2v.js
-'  392  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/k2v.js
-'  393  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/k2v.js
-'  1  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/julius
-'  613  0  ~/.vrapperrc
-'  1  0  ~/.vrapperrc
-'  144  44  ~/.zshrc
-'  1  0  ~/.zshrc
-'  150  0  ~/.zshrc
-'  145  72  ~/.zshrc
-'  144  21  ~/ProgramLocal/of_v0072_osx_release/apps/myApps/bgDiff/src/testApp.cpp
-'  115  3  ~/ProgramLocal/of_v0072_osx_release/apps/myApps/bgDiff/src/testApp.cpp
-'  94  33  ~/ProgramLocal/of_v0072_osx_release/apps/myApps/bgDiff/src/testApp.cpp
-'  44  84  ~/ProgramLocal/of_v0072_osx_release/apps/myApps/bgDiff/src/testApp.cpp
-'  26  0  ~/ProgramLocal/of_v0072_osx_release/apps/myApps/bgDiff/src/testApp.cpp
-'  51  0  ~/ProgramLocal/of_v0072_osx_release/apps/myApps/bgDiff/src/testApp.h
-'  1  0  ~/ProgramLocal/of_v0072_osx_release/apps/myApps/bgDiff/src/testApp.cpp
-'  228  16  ~/ProgramLocal/of_v0072_osx_release/apps/myApps/ofxBox2D/*vimshell* - default
-'  219  16  ~/ProgramLocal/of_v0072_osx_release/apps/myApps/ofxBox2D/*vimshell* - default
-'  8  82  ~/ProgramLocal/of_v0072_osx_release/apps/myApps/ofxBox2D/Project.xcconfig
-'  31  1  ~/ProgramLocal/of_v0072_osx_release/apps/myApps/ofxBox2D/*vimshell* - default
-'  7  18  ~/ProgramLocal/of_v0072_osx_release/apps/myApps/ofxBox2D/Project.xcconfig
-'  1  0  ~/ProgramLocal/of_v0072_osx_release/apps/myApps/ofxBox2D/Project.xcconfig
-'  8  18  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/package.json
-'  14  0  ~/Dropbox/Program/javascript/node.js/has/node_modules/julius/node_modules/kana2voca/package.json

# History of marks within files (newest to oldest):

> ~/Dropbox/dotfiles/.vimrc
	"	2	0
