# This viminfo file was generated by Vim 7.3.
# You may edit it if you're careful!

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~h
# Last Search Pattern:
~MSle0~/latest

# Last Substitute Search Pattern:
~MSle0&4.2.1

# Last Substitute String:
$

# Command Line History (newest to oldest):
:q
:wq
:Unite neobundle
:e bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
:w
:Ref alc l
:qa
:qa!
:Ref alc s
:NeoBundleClean
:source %
:qw
:'<,'>ContinuousNumber
:ContinuousNumber
:%S/prefix/subprefix/c
:echo $VIMRUNTIME
:echo $HOME
:'<,'>sort
:'<,'>Alignta 
:'<,'>Alignta

# Search String History (newest to oldest):
? \s\+$
?/latest
?/rainbow
?/rainbo
?/save_point
?/reanimate
?/save_dir
?/substitute
?/exception
?/call
?/g:
?/save
?/reanima
?/ttoc
?/continuous
?/subprefix
?/quickrun
?/tlib
?/,
?/cWORD

# Expression History (newest to oldest):

# Input Line History (newest to oldest):
@y
@test3
@test2
@test
@Test
@n
@hecomi
@node-julius
@寝ます…
@kるか
@アレ作ってるけど割りと作業感出てきた
@ssdp たたいて iRemocon 発見できるように出来ないかなー
@net.createConnection でいけそうだ。
@Node.js に TCP/IP でメッセージ送れるヤツあるかな。
@TL からピザの匂いがしてきた…
@うどん煮こむか
@風吹いてきた
@3 時くらいに昼飯食べたけどもうお腹すいてきた…
@あー、やっと直った…、時間浪費した…。
@あぁ、http と https 自動で割り振ってくれるのか。

# Input Line History (newest to oldest):

# Registers:
"0	CHAR	0
	g:reanimate_save_dir
""1	LINE	0
	
"2	LINE	0
	"autocmd FileType *   :RainbowParenthesesLoadRound
"3	LINE	0
	autocmd FileType cpp RainbowParenthesesLoadChevrons
"4	CHAR	0
	:
"5	CHAR	0
	\
"6	CHAR	0
	\
"7	CHAR	0
	~
"8	CHAR	0
	"
"9	CHAR	0
	.
"j	CHAR	0
	JJJJJJJKJJJJJJJ/power./g�kbfgnnnnnnnnnnnnnnnnnnnKKKK:messages:echo string(�kb�kb�kb�kb�kb�kb�kb�kb high�kb�kb�kb�kb�kb�kb�kb�kb�ku�ku�kd�kd�kbm�ku:echo hi['gui']
"k	CHAR	0
	k
"q	CHAR	0
	j
"-	CHAR	0
	:

# File marks:
'0  4  0  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
'1  6  0  ~/Dropbox/Program/javascript/node.js/julius/export_to_nodejs.cpp
'2  5  0  ~/Dropbox/Program/javascript/node.js/julius/export_to_nodejs.cpp
'3  972  32  ~/.vimrc
'4  917  0  ~/.vimrc
'5  911  0  ~/.vimrc
'6  2  0  ~/Dropbox/dotfiles
'7  6  0  ~/Dropbox/Program/javascript/node.js/test/mynode.js
'8  4  0  ~/Dropbox/Program/javascript/node.js/test/mynode.js
'9  966  42  ~/.vimrc

# Jumplist (newest first):
-'  4  0  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  1  0  ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
-'  6  0  ~/Dropbox/Program/javascript/node.js/julius/export_to_nodejs.cpp
-'  1  0  ~/Dropbox/Program/javascript/node.js/julius/export_to_nodejs.cpp
-'  5  0  ~/Dropbox/Program/javascript/node.js/julius/export_to_nodejs.cpp
-'  972  32  ~/.vimrc
-'  1  0  ~/.vimrc
-'  42  0  ~/Dropbox/Program/javascript/node.js/julius/export_to_nodejs.cpp
-'  917  0  ~/.vimrc
-'  524  0  ~/.vimrc
-'  103  0  ~/Dropbox/Program/javascript/node.js/julius/export_to_nodejs.cpp
-'  82  0  ~/Dropbox/Program/javascript/node.js/julius/export_to_nodejs.cpp
-'  911  0  ~/.vimrc
-'  913  4  ~/.vimrc
-'  893  3  ~/.vimrc
-'  263  16  ~/.vimrc
-'  47  3  ~/Dropbox/Program/javascript/node.js/julius/export_to_nodejs.cpp
-'  2  0  ~/Dropbox/dotfiles
-'  1  0  ~/Dropbox/dotfiles
-'  6  0  ~/Dropbox/Program/javascript/node.js/test/mynode.js
-'  5  0  ~/Dropbox/Program/javascript/node.js/test/mynode.js
-'  4  0  ~/Dropbox/Program/javascript/node.js/test/mynode.js
-'  1  0  ~/Dropbox/Program/javascript/node.js/test/mynode.js
-'  966  42  ~/.vimrc
-'  3  0  ~/Dropbox/Program/javascript/node.js/test/mynode.js
-'  873  0  ~/.vimrc
-'  963  2  ~/.vimrc
-'  276  26  ~/.vimrc
-'  74  36  ~/.vimrc
-'  2  0  ~/Dropbox/Program/javascript/node.js/test/mynode.js
-'  1026  0  ~/.vimrc
-'  1027  0  ~/.vimrc
-'  149  12  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  44  36  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  20  10  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  150  31  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  139  0  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  165  0  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  122  12  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  253  30  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  242  30  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  237  0  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  89  9  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  145  1  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  85  1  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  82  9  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  71  9  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  67  1  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  65  9  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  16  8  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  15  1  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  259  0  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  258  0  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  47  0  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  1  0  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  1  0  bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  967  4  ~/.vimrc
-'  198  0  ~/.vimrc
-'  3  0  ~/*unite* - default
-'  1  0  ~/*unite* - default
-'  93  0  ~/.vimrc
-'  91  0  ~/.vimrc
-'  936  0  ~/.vimrc
-'  100  13  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  99  23  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  80  29  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  63  40  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  52  20  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  48  22  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  43  20  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  37  28  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  36  27  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  264  8  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  263  13  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  243  22  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  202  0  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  3  0  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/plugin/reanimate.vim
-'  3  71  ~/Dropbox/dotfiles/.vim/*vimfiler* - default
-'  1  0  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/plugin/reanimate.vim
-'  1  0  ~/Dropbox/dotfiles/.vim/*vimfiler* - default
-'  215  1  ~/Dropbox/dotfiles/.vim/bundle/neobundle/plugins/vim-reanimate/autoload/reanimate.vim
-'  89  0  ~/.vimrc
-'  811  0  ~/.vimrc
-'  90  0  ~/.vimrc
-'  61  0  ~/yankring_history_v2.txt
-'  1  0  ~/yankring_history_v2.txt
-'  194  0  ~/.vimrc
-'  16  0  ~/vim_save_point/test/tmp/*vimfiler* - default
-'  1  0  ~/vim_save_point/test/tmp/*vimfiler* - default
-'  3  0  ~/.vimrc
-'  943  0  ~/sudo:.vimrc
-'  1  0  ~/sudo:.vimrc

# History of marks within files (newest to oldest):

> ~/Dropbox/Program/javascript/node.js/julius/*unite* - default
	"	3	0
	.	3	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	136	0
	+	134	0
	+	1	0
	+	132	0
	+	130	0
	+	1	0
	+	129	0
	+	126	0
	+	1	0
	+	123	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	120	0
	+	1	0
	+	118	0
	+	1	0
	+	116	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	111	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	104	0
	+	1	0
	+	96	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	24	0
	+	44	0
	+	64	0
	+	84	0
	+	93	0
	+	93	0
	+	93	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	13	0
	+	1	0
	+	1	0
	+	1	0
	+	1	0
	+	7	0
	+	5	0
	+	3	0

> ~/Dropbox/Program/javascript/node.js/julius/julius.cpp
	"	4	0
	.	228	0
	+	62	51
	+	71	9
	+	62	52
	+	71	37
	+	71	0
	+	71	47
	+	71	0
	+	71	18
	+	71	19
	+	64	0
	+	65	1
	+	65	0
	+	62	40
	+	71	0
	+	72	0
	+	71	15
	+	71	14
	+	71	0
	+	71	22
	+	71	16
	+	214	0
	+	215	19
	+	71	68
	+	65	0
	+	71	0
	+	71	12
	+	71	21
	+	92	0
	+	24	0
	+	22	16
	+	23	18
	+	21	0
	+	71	0
	+	69	15
	+	70	0
	+	67	0
	+	70	9
	+	62	66
	+	70	12
	+	71	0
	+	70	21
	+	92	36
	+	91	29
	+	91	99
	+	92	39
	+	16	0
	+	156	0
	+	163	0
	+	170	0
	+	129	0
	+	234	0
	+	236	0
	+	234	0
	+	235	0
	+	234	0
	+	235	0
	+	111	37
	+	47	0
	+	86	0
	+	97	0
	+	87	29
	+	87	0
	+	83	0
	+	83	14
	+	92	0
	+	91	0
	+	92	70
	+	82	0
	+	83	0
	+	86	0
	+	92	0
	+	91	0
	+	87	0
	+	97	0
	+	84	0
	+	235	0
	+	229	0
	+	234	0
	+	225	17
	+	75	0
	+	74	58
	+	225	0
	+	228	31
	+	225	6
	+	224	38
	+	227	3
	+	228	26
	+	228	0
	+	227	63
	+	16	0
	+	156	0
	+	163	0
	+	170	0
	+	17	21
	+	186	18
	+	228	0
	+	186	0
	+	228	8
	+	17	0
	+	228	0
