names=is_version_1_2?,version_1_2?
visibility=public
kind=defined

--- version_1_2? -> true
--- is_version_1_2? -> true
何もしません。互換性のために残されており、常に true を返します。

@see [[m:Net::HTTP.version_1_2]], [[m:Net::HTTP.version_1_1?]]

